topdir=../../../../

#OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o capt_seq.o movie_rec.o
#STUBS_AUTO_DEPS=boot.c capt_seq.c movie_rec.c

OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o capt_seq.o debug.o ../../leds.o
STUBS_AUTO_DEPS=boot.c capt_seq.c debug.c

include  $(topdir)platform/makefile_sub.inc
