#include "stubs_asm.h"

//NHSTUB(VbattGet, 0xFFC1B4CC)
//NHSTUB(GetZoomLensCurrentPosition, 0xFFE53070)
//NHSTUB(GetZoomLensCurrentPoint, 0xFFE5305C)
//NHSTUB(GetFocusLensSubjectDistance, 0xFFE667F0)
//NHSTUB(malloc, 0xFFEBEE9C)
//NHSTUB(free, 0xFFEBEEA8)

//NHSTUB(MoveFocusLensWithDistance, 0xFFE67B14)
//NHSTUB(MoveZoomLensWithPoint, 0xFFE52F3C)
//NHSTUB(MoveZoomLensWithPosition, 0xFFE52FB8)
//NHSTUB(GetFocusLensCurrentPosition, 0xFFE67F10)
//NHSTUB(MoveFocusLensWithPosition, 0xFFE67CB4)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFFC20AD4)  //null stub

