#!build time optional components - comment out the features you dont want to have in your build
OPT_LUA_IOLIB=1
OPT_LUA_OSLIB=1
OPT_GAME_REVERSI=1
OPT_GAME_SOKOBAN=1
OPT_GAME_CONNECT4=1
OPT_BOOTLOGO=1
OPT_CURVES=1
OPT_TEXTREADER=1
OPT_CALENDAR=1
OPT_DEBUGGING=1
OPT_EDGEOVERLAY=1
OPT_LUA_STRLIB=1
#!OPT_UBASIC=1              // Shall ubasic be compiled into build? not done yet
#!OPT_LUA=1                 // Shall lua support be compiled into build? not done yet
#!OPT_SYMBOLS=1             // the symbols / not done yet
#!OPT_LANGUAGEINTERFACE=1   // for people who won't use lang files at all / not done yer
