#include "conf.h"

// TODO - is this needed
void change_video_tables(int a, int b){
}

void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}

// @ FF987094
void __attribute__((naked,noinline)) movie_record_task(){ 

 asm volatile(
"                STMFD   SP!, {R2-R10,LR} \n"
"                LDR     R8, =0x2710 \n"
"                LDR     R4, =0x7290 \n"
"                MOV     R7, #1 \n"
"                LDR     R6, =0xFF986D84 \n"
"                MOV     R5, #0 \n"

"loc_FF9870AC: \n"
"                LDR     R0, [R4,#0x24] \n"
"                MOV     R2, #0 \n"
"                ADD     R1, SP, #4 \n"
"                BL      sub_FF83A460 \n"
"                LDR     R0, [R4,#0x2C] \n"
"                CMP     R0, #0 \n"
"                LDRNE   R0, [R4,#0xC] \n"
"                CMPNE   R0, #2 \n"
"                LDRNE   R0, [R4,#0x44] \n"
"                CMPNE   R0, #6 \n"
"                BNE     loc_FF9871C4 \n"
"                LDR     R0, [SP,#4] \n"
"                LDR     R1, [R0] \n"
"                SUB     R1, R1, #2 \n"
"                CMP     R1, #0xA \n"
"                ADDLS   PC, PC, R1,LSL#2 \n"

"                B       loc_FF9871C4 \n"
"loc_FF9870F0: \n"
"                B       loc_FF987178 \n"
"loc_FF9870F4: \n"
"                B       loc_FF987198 \n"
"loc_FF9870F8: \n"
"                B       loc_FF9871A8 \n"
"loc_FF9870FC: \n"
"                B       loc_FF9871B0 \n"
"loc_FF987100: \n"
"                B       loc_FF987180 \n"
"loc_FF987104: \n"
"                B       loc_FF9871B8 \n"
"loc_FF987108: \n"
"                B       loc_FF987188 \n"
"loc_FF98710C: \n"
"                B       loc_FF9871C4 \n"
"loc_FF987110: \n"
"                B       loc_FF9871C0 \n"
"loc_FF987114: \n"
"                B       loc_FF987148 \n"
"loc_FF987118: \n"
"                B       loc_FF98711C \n"

"loc_FF98711C: \n"
//"; jumptable entry 10 \n"
"                STR     R5, [R4,#0x40] \n"
"                STR     R5, [R4,#0x30] \n"
"                STR     R5, [R4,#0x34] \n"
"                STRH    R5, [R4,#6] \n"
"                STR     R6, [R4,#0xB4] \n"
"                LDR     R0, [R4,#0xC] \n"
"                ADD     R0, R0, #1 \n"
"                STR     R0, [R4,#0xC] \n"
"                MOV     R0, #6 \n"
"                STR     R0, [R4,#0x44] \n"
"                B       loc_FF987164 \n"

"loc_FF987148: \n"
//"; jumptable entry 9 \n"
"                STR     R5, [R4,#0x40] \n"
"                STR     R5, [R4,#0x30] \n"
"                STR     R6, [R4,#0xB4] \n"
"                LDR     R0, [R4,#0xC] \n"
"                ADD     R0, R0, #1 \n"
"                STR     R0, [R4,#0xC] \n"
"                STR     R7, [R4,#0x44] \n"

"loc_FF987164: \n"
"                LDR     R2, =0xFF985F9C \n"
"                LDR     R1, =0xB3E0C \n"
"                LDR     R0, =0xFF986098 \n"
"                BL      sub_FF8532D0 \n"
"                B       loc_FF9871C4 \n"

"loc_FF987178: \n"
//"; jumptable entry 0            ; LOCATION: MovieRecorder.c:0 \n"

"		BL	unlock_optical_zoom\n" 			// added to unlock the zoom

"                BL      sub_FF986EAC \n"
"                B       loc_FF9871C4 \n"

"loc_FF987180: \n"
//"; jumptable entry 4            ; LOCATION: MovieRecorder.c:2032 \n"
//"                BL      sub_FF9867EC \n"
"                BL      sub_FF9867EC_my \n"		// patched
"                B       loc_FF9871C4 \n"

"loc_FF987188: \n"
//"; jumptable entry 6 \n"
"				LDR		R1, [R0,#0x18] \n"
"				LDR		R0, [R0,#4] \n"
"                BL      sub_FFB00134 \n"
"                B       loc_FF9871C4 \n"

"loc_FF987198: \n"
//"; jumptable entry 1 \n"
"                LDR     R0, [R4,#0x44] \n"
"                CMP     R0, #5 \n"
"                STRNE   R7, [R4,#0x34] \n"
"                B       loc_FF9871C4 \n"

"loc_FF9871A8: \n"
//"; jumptable entry 2            ; LOCATION: MovieRecorder.c:1000 \n"
"                BL      sub_FF986434 \n"
"                B       loc_FF9871C4 \n"

"loc_FF9871B0: \n"
//"; jumptable entry 3            ; LOCATION: MovieRecorder.c:0 \n"
"                BL      sub_FF9860E4 \n"
"                B       loc_FF9871C4 \n"

"loc_FF9871B8: \n"
//"; jumptable entry 5            ; LOCATION: MovieRecorder.c:100 \n"
"                BL      sub_FF985F28 \n"
"                B       loc_FF9871C4 \n"

"loc_FF9871C0: \n"
//"; jumptable entry 8            ; LOCATION: MovieRecorder.c:0 \n"
"                BL      sub_FF9875F4 \n"

"loc_FF9871C4: \n"
//"; jumptable default entry \n"
//"; jumptable entry 7 \n"
"                LDR     R1, [SP,#4] \n"
"				 MOV	 R3, #0x5F0 \n"
"                STR     R5, [R1] \n"
"                STR     R3, [SP] \n"
"                LDR     R0, [R4,#0x28] \n"
"                LDR     R3, =0xFF985D8C \n" //;aMovierecorder_
"                MOV     R2, R8 \n"
"                BL      sub_FF83ADB4 \n"
"                B       loc_FF9870AC \n"
 );
}

// TODO - can this be shrunk by jumping to firmware locations after patches ???
void __attribute__((naked,noinline)) sub_FF9867EC_my(){ 
 asm volatile(
"                STMFD   SP!, {R4-R11,LR} \n"
"                SUB     SP, SP, #0x64 \n"
"                MOV     R8, #0 \n"
"                LDR     R6, =0x7290 \n"
"                MOV     R4, R0 \n"
"                STR     R8, [SP,#0x54] \n"
"                STR     R8, [SP,#0x4C] \n"
"                LDR     R0, [R6,#0x44] \n"
"                MOV     R11, #4 \n"
"                CMP     R0, #3 \n"
"                STREQ   R11, [R6,#0x44] \n"
"                LDR     R0, [R6,#0xB4] \n"
"                MOV     R9, #0 \n"
"                MOV     R7, #0 \n"
"                MOV     R5, #1 \n"
"                BLX     R0 \n"
"                LDR     R0, [R6,#0x44] \n"
"                CMP     R0, #6 \n"
"                BEQ     loc_FF98684C \n"
"                LDR     R1, [R6,#0xC] \n"
"                CMP     R1, #2 \n"
"                BNE     loc_FF98686C \n"
"                CMP     R0, #5 \n"
"                BEQ     loc_FF9868E4 \n"

"loc_FF98684C: \n"
"                LDR     R1, =0x7F2 \n"
"                MOV     R7, #1 \n"
"                LDR     R0, =0xFF985D8C \n"	//aMovierecorder_
"                BL      _DebugAssert \n"
"                LDR     R0, [R6,#0x44] \n"
"                CMP     R0, #4 \n"
"                MOVNE   R5, #0 \n"
"                B       loc_FF986874 \n"

"loc_FF98686C: \n"
"                CMP     R0, #4 \n"
"                BNE     loc_FF9868E4 \n"

"loc_FF986874: \n"
"                LDRH    R0, [R6,#6] \n"
"                CMP     R0, #1 \n"
"                LDREQ   R1, =0x809 \n"
"                LDREQ   R0, =0xFF985D8C \n"	//aMovierecorder_
"                BLEQ    _DebugAssert \n"
"                LDRH    R0, [R6,#6] \n"
"                CMP     R0, #3 \n"
"                BNE     loc_FF9868A8 \n"
"                LDR     R0, [R6,#0x6C] \n"
"                LDR     R1, [R6,#0xB8] \n"
"                BL      sub_FFBB5A40 \n"
"                CMP     R1, #0 \n"
"                MOVNE   R5, #0 \n"

"loc_FF9868A8: \n"
"                LDR     R0, [R6,#0x44] \n"
"                CMP     R0, #6 \n"
"                CMPNE   R0, #1 \n"
"                CMPNE   R0, #3 \n"
"                BNE     loc_FF9868EC \n"
"                CMP     R7, #1 \n"
"                CMPEQ   R5, #0 \n"
"                BNE     loc_FF9868EC \n"
"                LDR     R0, [R6,#0x18] \n"
"                MOV     R1, #0x3E8 \n"
"                BL      _eventproc_export_TakeSemaphore \n"
"                CMP     R0, #9 \n"
"                BNE     loc_FF986D0C \n"
"                MOV     R0, #0x90000 \n"
"                BL      _eventproc_export_HardwareDefect \n"

"loc_FF9868E4: \n"
"                ADD     SP, SP, #0x64 \n"
"                LDMFD   SP!, {R4-R11,PC} \n"

"loc_FF9868EC: \n"
"                CMP     R5, #1 \n"
"                MOV     R10, #1 \n"
"                BNE     loc_FF986914 \n"
"                ADD     R3, SP, #0x4c \n"
"                ADD     R2, SP, #0x50 \n"
"                ADD     R1, SP, #0x54 \n"
"                ADD     R0, SP, #0x58 \n"
"                BL      sub_FFB001F4 \n"
"                MOVS    R9, R0 \n"
"                BNE     loc_FF986930 \n"

"loc_FF986914: \n"
"                LDR     R0, [R6,#0x34] \n"
"                CMP     R0, #1 \n"
"                BNE     loc_FF986A8C \n"
"                LDR     R0, [R6,#0x6C] \n"
"                LDR     R1, [R6,#0x48] \n"
"                CMP     R0, R1 \n"
"                BCC     loc_FF986A8C \n"

"loc_FF986930: \n"
"                CMP     R9, #0x80000001 \n"
"                STREQ   R11, [R6,#0x70] \n"
"                BEQ     loc_FF986968 \n"
"                CMP     R9, #0x80000003 \n"
"                STREQ   R10, [R6,#0x70] \n"
"                BEQ     loc_FF986968 \n"
"                CMP     R9, #0x80000005 \n"
"                MOVEQ   R0, #2 \n"
"                BEQ     loc_FF986964 \n"
"                CMP     R9, #0x80000007 \n"
"                STRNE   R8, [R6,#0x70] \n"
"                BNE     loc_FF986968 \n"
"                MOV     R0, #3 \n"

"loc_FF986964: \n"
"                STR     R0, [R6,#0x70] \n"

"loc_FF986968: \n"
"                LDR     R0, [R6,#0xC] \n"
"                CMP     R0, #2 \n"
"                BNE     loc_FF9869D0 \n"
"                MOV     R1, #0 \n"
"                LDR     R0, =0xFF9867E0 \n"
"                BL      sub_FFABBE18 \n"
"                LDR     R2, [R6,#0x64] \n"
"                ADD     R3, SP, #0x5c \n"
"                STRD    R2, [SP,#0x28] \n"
"                MOV     R2, #0x18 \n"
"                ADD     R1, SP, #0x34 \n"
"                ADD     R0, SP, #0x10 \n"
"                BL      sub_FFBB33E0 \n"
"                LDR     R1, [R6,#0x84] \n"
"                LDR     R2, [R6,#0x88] \n"
"                MVN     R3, #1 \n"	//0xFFFFFFFE \n"
"                ADD     R0, SP, #0x60 \n"
"                STMEA   SP, {R0-R3} \n"
"                LDR     R0, =0xB3E54 \n"
"                MOV     R3, #0 \n"
"                MOV     R2, #0 \n"
"                MOV     R1, #0x40 \n"
"                BL      sub_FFABBD70 \n"
"                B       loc_FF986A24 \n"

"loc_FF9869C8: \n"
"                MOV     R1, #1 \n"
"                B       loc_FF986C98 \n"

"loc_FF9869D0: \n"
"                BL      sub_FF9876A0 \n"
"                LDR     R2, [R6,#0x64] \n"
"                ADD     R3, SP, #0x5c \n"
"                MVN     R1, #1 \n"	//0xFFFFFFFE \n"
"                MOV     R0, #0 \n"
"                ADD     R5, SP, #0x1c \n"
"                STMIA   R5, {R0-R3} \n"
"                LDR     R3, [R4,#0x1C] \n"
"                LDR     R1, [R6,#0x84] \n"
"                LDR     R2, [R6,#0x88] \n"
"                ADD     R4, SP, #0x0c \n"
"                ADD     R0, SP, #0x60 \n"
"                STMIA   R4, {R0-R3} \n"
"                MOV     R3, #0 \n"
"                MOV     R1, #0x40 \n"
"                MOV     R2, #0 \n"
"                STMEA   SP, {R1-R3} \n"
"                LDR     R3, =0xB3E54 \n"
"                MOV     R1, #0 \n"
"                MOV     R0, #0 \n"
"                BL      sub_FFABABE0 \n"

"loc_FF986A24: \n"
"                LDR     R0, [R6,#0x18] \n"
"                LDR     R1, [R6,#0x60] \n"
"                BL      _eventproc_export_TakeSemaphore \n"
"                CMP     R0, #9 \n"
"                BEQ     loc_FF9869C8 \n"
"                LDR     R0, [SP,#0x5c] \n"
"                CMP     R0, #0 \n"
"                BEQ     loc_FF986A4C \n"

"loc_FF986A44: \n"
"                MOV     R1, #1 \n"
"                B       loc_FF986CB0 \n"

"loc_FF986A4C: \n"
"                LDR     R0, [R6,#0xC] \n"
"                MOV     R4, #5 \n"
"                CMP     R0, #2 \n"
"                MOV     R0, #1 \n"
"                BNE     loc_FF986A78 \n"
"                BL      sub_FFABBDD8 \n"
"                BL      sub_FFABBE00 \n"
"                STR     R4, [R6,#0x44] \n"
"                BL      sub_FF9876A0 \n"
"                STR     R10, [R6,#0x44] \n"
"                B       loc_FF986A84 \n"

"loc_FF986A78: \n"
"                BL      sub_FFABAC94 \n"
"                BL      sub_FFABACF4 \n"
"                STR     R4, [R6,#0x44] \n"

"loc_FF986A84: \n"
"                STR     R8, [R6,#0x34] \n"
"                B       loc_FF9868E4 \n"

"loc_FF986A8C: \n"
"                CMP     R5, #1 \n"
"                BNE     loc_FF986D0C \n"
"                STR     R10, [R6,#0x38] \n"
"                LDR     R0, [R6,#0x6C] \n"
"                LDR     R11, [R4,#0xC] \n"
"                CMP     R0, #0 \n"
"                LDRNE   R9, [SP,#0x58] \n"
"                LDRNE   R10, [SP,#0x54] \n"
"                BNE     loc_FF986BD4 \n"
"                LDR     R0, [R6,#0xC] \n"
"                CMP     R0, #2 \n"
"                BNE     loc_FF986B30 \n"
"                MOV     R1, #0 \n"
"                LDR     R0, =0xFF9867E0 \n"
"                BL      sub_FFABBE18 \n"
"                LDR     R2, [R6,#0x64] \n"
"                ADD     R3, SP, #0x5c \n"
"                STRD    R2, [SP,#0x28] \n"
"                MOV     R2, #0x18 \n"
"                ADD     R1, SP, #0x34 \n"
"                ADD     R0, SP, #0x10 \n"
"                BL      sub_FFBB33E0 \n"
"                LDR     R1, [R6,#0x84] \n"
"                LDR     R2, [R6,#0x88] \n"
"                MVN     R3, #0 \n"	//0xFFFFFFFF \n"
"                ADD     R0, SP, #0x60 \n"
"                STMEA   SP, {R0-R3} \n"
"                LDR     R0, [SP,#0x58] \n"
"                LDR     R1, [SP,#0x54] \n"
"                LDR     R2, [SP,#0x50] \n"
"                LDR     R3, [SP,#0x4c] \n"
"                BL      sub_FFABBD70 \n"
"                LDR     R0, [R6,#0x18] \n"
"                LDR     R1, [R6,#0x60] \n"
"                BL      _eventproc_export_TakeSemaphore \n"
"                CMP     R0, #9 \n"
"                BEQ     loc_FF9869C8 \n"
"                MOV     R1, #0 \n"
"                LDR     R0, =0xFF9867D4 \n"
"                BL      sub_FFABBE18 \n"
"                B       loc_FF986B98 \n"

"loc_FF986B30: \n"
"                LDR     R0, [R4,#0x20] \n"
"                LDR     R2, [R6,#0x64] \n"
"                ADD     R3, SP, #0x5c \n"
"                MVN     R1, #0 \n"	//0xFFFFFFFF \n"
"                ADD     R9, SP, #0x1c \n"
"                STMIA   R9, {R0-R3} \n"
"                LDR     R3, [R4,#0x1C] \n"
"                LDR     R1, [R6,#0x84] \n"
"                LDR     R2, [R6,#0x88] \n"
"                ADD     R0, SP, #0x60 \n"
"                ADD     R9, SP, #0x0c \n"
"                STMIA   R9, {R0-R3} \n"
"                LDR     R1, [SP,#0x50] \n"
"                LDR     R2, [SP,#0x54] \n"
"                LDR     R3, [SP,#0x4c] \n"
"                STMFA   SP, {R1,R3} \n"
"                STR     R2, [SP] \n"
"                LDMIB   R4, {R0,R1} \n"
"                LDR     R3, [SP,#0x58] \n"
"                MOV     R2, R11 \n"
"                BL      sub_FFABABE0 \n"
"                LDR     R0, [R6,#0x18] \n"
"                LDR     R1, [R6,#0x60] \n"
"                BL      _eventproc_export_TakeSemaphore \n"
"                CMP     R0, #9 \n"
"                BEQ     loc_FF9869C8 \n"

"loc_FF986B98: \n"
"                LDR     R0, [SP,#0x5c] \n"
"                CMP     R0, #0 \n"
"                BNE     loc_FF986A44 \n"
"                LDR     R0, [R6,#0xC] \n"
"                CMP     R0, #2 \n"
"                MOV     R0, #1 \n"
"                BNE     loc_FF986BBC \n"
"                BL      sub_FFABBDD8 \n"
"                B       loc_FF986BC0 \n"

"loc_FF986BBC: \n"
"                BL      sub_FFABAC94 \n"

"loc_FF986BC0: \n"
"                LDR     R0, [SP,#0x60] \n"
"                LDR     R1, [SP,#0x58] \n"
"                ADD     R9, R1, R0 \n"
"                LDR     R1, [SP,#0x54] \n"
"                SUB     R10, R1, R0 \n"

"loc_FF986BD4: \n"
"                LDR     R0, [R6,#0xC] \n"
"                LDR     R2, [R6,#0x64] \n"
"                CMP     R0, #2 \n"
"                ADD     R3, SP, #0x5c \n"
"                BNE     loc_FF986C28 \n"
"                STRD    R2, [SP,#0x28] \n"
"                MOV     R2, #0x18 \n"
"                ADD     R1, SP, #0x34 \n"
"                ADD     R0, SP, #0x10 \n"
"                BL      sub_FFBB33E0 \n"
"                LDR     R1, [R6,#0x84] \n"
"                LDR     R2, [R6,#0x88] \n"
"                LDR     R3, [R6,#0x68] \n"
"                ADD     R0, SP, #0x60 \n"
"                STMEA   SP, {R0-R3} \n"
"                LDR     R2, [SP,#0x50] \n"
"                LDR     R3, [SP,#0x4c] \n"
"                MOV     R1, R10 \n"
"                MOV     R0, R9 \n"
"                BL      sub_FFABBD70 \n"
"                B       loc_FF986C80 \n"

"loc_FF986C28: \n"
"                LDR     R1, [R6,#0x68] \n"
"                LDR     R0, [R4,#0x20] \n"
"                STR     R1, [SP,#0x20] \n"
"                STR     R0, [SP,#0x1c] \n"
"                STR     R2, [SP,#0x24] \n"
"                STR     R3, [SP,#0x28] \n"
"                LDR     R3, [R4,#0x1C] \n"
"                LDR     R1, [R6,#0x84] \n"
"                LDR     R2, [R6,#0x88] \n"
"                ADD     R0, SP, #0x60 \n"
"                STR     R2, [SP,#0x14] \n"
"                LDR     R2, [SP,#0x50] \n"
"                STR     R1, [SP,#0x10] \n"
"                STR     R3, [SP,#0x18] \n"
"                LDR     R3, [SP,#0x4c] \n"
"                STR     R0, [SP,#0x0c] \n"
"                STMFA   SP, {R2,R3} \n"
"                STR     R10, [SP] \n"
"                LDMIB   R4, {R0,R1} \n"
"                MOV     R3, R9 \n"
"                MOV     R2, R11 \n"
"                BL      sub_FFABABE0 \n"

"loc_FF986C80: \n"
"                LDR     R0, [R6,#0x18] \n"
"                LDR     R1, [R6,#0x60] \n"
"                BL      _eventproc_export_TakeSemaphore \n"
"                CMP     R0, #9 \n"
"                BNE     loc_FF986CA0 \n"
"                MOV     R1, #0 \n"

"loc_FF986C98: \n"
"                MOV     R0, #0x90000 \n"
"                B       loc_FF986CB4 \n"

"loc_FF986CA0: \n"
"                LDR     R0, [SP,#0x5c] \n"
"                CMP     R0, #0 \n"
"                BEQ     loc_FF986CBC \n"
"                MOV     R1, #0 \n"

"loc_FF986CB0: \n"
"                MOV     R0, #0xA0000 \n"

"loc_FF986CB4: \n"
"                BL      sub_FF986774 \n"
"                B       loc_FF9868E4 \n"

"loc_FF986CBC: \n"
"                LDR     R0, [R6,#0xC] \n"
"                CMP     R0, #2 \n"
"                MOV     R0, #0 \n"
"                BNE     loc_FF986CD4 \n"
"                BL      sub_FFABBDD8 \n"
"                B       loc_FF986CD8 \n"

"loc_FF986CD4: \n"
"                BL      sub_FFABAC94 \n"

"loc_FF986CD8: \n"
"                LDR     R0, [SP,#0x58] \n"
"                LDR     R1, [SP,#0x60] \n"
"                BL      sub_FFB0042C \n"
"                LDR     R0, [R6,#0x68] \n"
"                LDR     R3, =0x7318 \n"
"                ADD     R1, R0, #1 \n"
"                STR     R1, [R6,#0x68] \n"
"                STR     R3, [SP] \n"
"                LDR     R0, [R6,#0x64] \n"
"                SUB     R3, R3, #4 \n"
"                AND     R2, R0, #0xFF \n"
"                LDR     R0, [SP,#0x60] \n"
"                BL      sub_FFAFDF74 \n"

                "LDR     R0, =0x7318-4\n" // <----   -4 //+
                "BL      set_quality\n"                 //+

"loc_FF986D0C: \n"
"                CMP     R5, #1 \n"
"                LDRNEH  R0, [R6,#6] \n"
"                CMPNE   R0, #3 \n"
"                BNE     loc_FF9868E4 \n"
"                LDR     R0, [R6,#0x6C] \n"
"                ADD     R0, R0, #1 \n"
"                STR     R0, [R6,#0x6C] \n"
"                LDRH    R1, [R6,#6] \n"
"                CMP     R1, #3 \n"
"                LDRNE   R1, [R6,#0x54] \n"
"                LDREQ   R1, =0x3E9 \n"
"                MUL     R0, R1, R0 \n"
"                LDREQ   R1, =0x1770 \n"
"                LDRNE   R1, [R6,#0x50] \n"
"                BL      sub_FFBB5A40 \n"
"                MOV     R4, R0 \n"
"                BL      sub_FFB007A8 \n"
"                LDR     R0, [R6,#0x8C] \n"
"                CMP     R0, R4 \n"
"                BNE     loc_FF986D68 \n"
"                LDR     R0, [R6,#0x3C] \n"
"                CMP     R0, #1 \n"
"                BNE     loc_FF986D7C \n"

"loc_FF986D68: \n"
"                LDR     R1, [R6,#0x98] \n"
"                MOV     R0, R4 \n"
"                BLX     R1 \n"
"                STR     R4, [R6,#0x8C] \n"
"                STR     R8, [R6,#0x3C] \n"

"loc_FF986D7C: \n"
"                STR     R8, [R6,#0x38] \n"
"                B       loc_FF9868E4 \n"
	);
}
