#include "stubs_asm.h"

DEF(physw_status, 0x45DC8)
DEF(physw_run, 0x8FF0)
DEF(zoom_busy, 0x6D910)          
DEF(focus_busy, 0x6D390)
DEF(FlashParamsTable,0xFFEADA5C)
DEF(canon_menu_active,0x2EE4) 
DEF(canon_ev_corr_menu_active, 0xD5D8)
DEF(canon_shoot_menu_active,0xD504)
DEF(recreview_hold, 0x2590)
DEF(movie_status, 0x91D54)  
DEF(some_flag_for_af_scan, 0xCF88)
DEF(zoom_status, 0x2658)
DEF(some_f_for_dng, 0x6184)
DEF(second_ext_for_dng, 0x61A8)
DEF(levent_table,0xFFE9EC88)
DEF(playrec_mode,0xD29C) // "SSAPI::MenuIn"
