#include "stubs_asm.h"

//DEF(physw_status, 0xFB20)
DEF(physw_status, 0xFB20)
DEF(led_table, 0x7703C)

DEF(zoom_busy, 0x76B4C)
DEF(focus_busy, 0x76E4C)
DEF(FlashParamsTable,0xFF969790)
DEF(canon_menu_active,0x72C8)
DEF(canon_shoot_menu_active,0x65B5)
DEF(recreview_hold, 0x739F8)
DEF(zoom_status, 0x64C0)
DEF(movie_status, 0x6F684)
DEF(some_flag_for_af_scan, 0xFFFF0000) // dummy
DEF(some_f_for_dng, 0x800C)
DEF(second_ext_for_dng, 0x8030)
DEF(levent_table,0xFF962594)
