topdir=../../../../

OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o capt_seq.o movie_rec.o mount.o
STUBS_AUTO_DEPS=boot.c capt_seq.c movie_rec.c mount.c

include  $(topdir)platform/makefile_sub.inc
