#include "stubs_asm.h"

DEF(zoom_busy, 0x7070+0x14)					// @FF9809C8
DEF(focus_busy, 0x6f28 + 8)					// @FF97BEC8
DEF(zoom_status, 0x835C) 					// @FF9C21FC
DEF(canon_menu_active, 0x324c + 4)			// @FF896FC0
DEF(movie_status, 0x7128 + 0x44)			// @FF985B90
DEF(enabled_refresh_physical_screen, 0xA0D4) // @FFA4760C
DEF(playrec_mode, 0x2f74+0x4)				// @FF889094
DEF(FlashParamsTable,0xFFC724C4)			// @FFB0F34C
DEF(physw_status, 0x34CB4)                 	// @FF8340C8
DEF(physw_run, 0x1C30 + 0x0C)            	// @FF8340A4
DEF(led_table, 0x25d4 + 0x04)				// @FF864814
DEF(some_flag_for_af_scan, 0x7534)			// @FF9894C0
DEF(canon_shoot_menu_active, 0x8758 + 1)	// @FF9D7B7C
DEF(levent_table,0xFFBF5E0C)				// @FF9B8354
DEF(recreview_hold, 0x81f8+0xE8)			// @FF9BDC84
