void __attribute__((naked,noinline)) init_file_modules_task(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "BL      _Unmount_FileSystem\n" // + 
                "BL      sub_FFC0C954\n"
                "SUBS    R4, R0, #0\n"
                "MOV     R0, #0x5000\n"
                "MOV     R1, #0\n"
                "ADD     R0, R0, #6\n"
                "BEQ     loc_FFC13DC0\n"
                "BL      sub_FFEDC848\n"
"loc_FFC13DC0:\n"
                "BL      sub_FFC0C980_my\n"  //------------->
                "MOV     R0, #0x5000\n"
                "CMP     R4, #0\n"
                "MOV     R1, R4\n"
                "ADD     R0, R0, #6\n"
                "LDMNEFD SP!, {R4,PC}\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFEDC848\n"
 );
}

void __attribute__((naked,noinline)) sub_FFC0C980_my(){
 asm volatile(
                "STR     LR, [SP,#-4]!\n"
                "BL      Mount_FileSystem_my\n" //--------------->
                "LDR     R3, =0x1E0C\n"
                "LDR     R2, [R3]\n"
                "CMP     R2, #0\n"
                "BNE     loc_FFC0C9BC\n"
                "BL      sub_FFC34A7C\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFE1F1F8\n"
                "BL      sub_FFC34A7C\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFE2D460\n"
                "BL      sub_FFC34A8C\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFE1F2E0\n"
"loc_FFC0C9BC:\n"
                "LDR     R2, =0x1E08\n"
                "MOV     R3, #1\n"
                "STR     R3, [R2]\n"
                "LDR     PC, [SP],#4\n"
 );
}

void __attribute__((naked,noinline)) Mount_FileSystem_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "MOV     R4, #0\n"
                "MOV     R5, R4\n"
                "LDR     R6, =0x74A88\n"
                "MOV     R0, R5\n"
                "BL      sub_FFE45858\n"
                "LDR     R0, [R6,#0x38]\n"
                "BL      sub_FFE44EEC\n"
                "CMP     R0, R4\n"
                "MOV     R1, R5\n"
                "MOV     R0, R5\n"
                "BNE     loc_FFE45EC4\n"
                "LDR     R3, =0x9774\n"
                "LDR     R2, =0x976C\n"
                "STR     R1, [R3]\n"
                "LDR     R3, =0x9770\n"
                "STR     R1, [R2]\n"
                "STR     R1, [R3]\n"
"loc_FFE45EC4:\n"
                "BL      sub_FFE458A8\n"
                "MOV     R0, R5\n"
                "BL      sub_FFE45BD8_my\n"  //---------------->
                "MOV     R4, R0\n"
                "MOV     R0, R5\n"
                "BL      sub_FFE45C60\n"
                "LDR     R1, [R6,#0x3C]\n"
                "AND     R2, R4, R0\n"
                "MOV     R0, R6\n"
                "BL      sub_FFE45E2C\n"
                "STR     R0, [R6,#0x40]\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFE45BD8_my(){
 asm volatile(
                "STMFD   SP!, {R4-R7,LR}\n"
                "LDR     R7, =0x9770\n"
                "LDR     R3, [R7]\n"
                "MOV     R4, R0\n"
                "CMP     R3, #0\n"
                "ADD     R3, R4, R4,LSL#1\n"
                "RSB     R3, R4, R3,LSL#3\n"
                "LDR     R6, =0x74AC0\n"
                "MOV     R5, R3,LSL#2\n"
                "MOV     R1, R4\n"
                "BNE     loc_FFE45C4C\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFE45960_my\n"   //--------------------->
                "SUBS    R3, R0, #0\n"
                "MOV     R1, R4\n"
                "BEQ     loc_FFE45C24\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFE45AB4\n"
                "MOV     R3, R0\n"
"loc_FFE45C24:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R4\n"
                "BEQ     loc_FFE45C38\n"
                "BL      sub_FFE44FC4\n"
                "MOV     R3, R0\n"
"loc_FFE45C38:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R3\n"
                "MOVNE   R3, #1\n"
                "STRNE   R3, [R7]\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
"loc_FFE45C4C:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFE45960_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R5, R1\n"
                "MOV     R8, R5,LSL#1\n"
                "ADD     R3, R8, R5\n"
                "LDR     R2, =0x74AC4\n"
                "SUB     SP, SP, #8\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "LDR     R1, [R2,R3,LSL#2]\n"
                "MOV     R6, #0\n"
                "STR     R6, [SP]\n"
                "MOV     R7, R0\n"
                "STR     R6, [SP,#4]\n"
                "CMP     R1, #6\n"
                "LDRLS   PC, [PC,R1,LSL#2]\n"
                "B       loc_FFE45A60\n"
                ".long loc_FFE45A04\n"
                ".long loc_FFE459B8\n"
                ".long loc_FFE459B8\n"
                ".long loc_FFE459B8\n"
                ".long loc_FFE459B8\n"
                ".long loc_FFE45A50\n"
                ".long loc_FFE459B8\n"
"loc_FFE459B8:\n"
                "MOV     R0, #3\n"
                "MOV     R1, #0x200\n"
                "MOV     R2, #0\n"
                "BL      sub_FFC0E2AC\n"
                "SUBS    R6, R0, #0\n"
                "BEQ     loc_FFE45A98\n"
                "ADD     R12, R8, R5\n"
                "RSB     R12, R5, R12,LSL#3\n"
                "LDR     R4, =0x74AD4\n"
                "MOV     R0, R7\n"
                "MOV     R1, #0\n"
                "MOV     R2, #1\n"
                "MOV     R3, R6\n"
                "MOV     LR, PC\n"
                "LDR     PC, [R4,R12,LSL#2]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFE45A0C\n"
                "MOV     R0, #3\n"
                "BL      sub_FFC0E37C\n"
"loc_FFE45A04:\n"
                "MOV     R0, #0\n"
                "B       loc_FFE45A98\n"
"loc_FFE45A0C:\n"
                "MOV     R0, R7\n"
                "BL      sub_FFE59444\n"
                "MOV     R1, R0\n"
                "ADD     R2, SP, #4\n"
                "MOV     R3, SP\n"
                "MOV     R0, R6\n"

                "STMFD   SP!, {R4-R11,LR}\n" // +
                "BL      mbr_read\n"    //-----------> 
                "LDMFD   SP!, {R4-R11,LR}\n" // +

          //    "BL      sub_FFE450F0\n"      // original function
                "MOV     R4, R0\n"
                "MOV     R0, #3\n"
                "BL      sub_FFC0E37C\n"
                "CMP     R4, #0\n"
                "BNE     loc_FFE45A70\n"
                "MOV     R0, R7\n"
                "STR     R4, [SP,#4]\n"
                "BL      sub_FFE59444\n"
                "STR     R0, [SP]\n"
                "B       loc_FFE45A70\n"
"loc_FFE45A50:\n"
                "MOV     R3, #0\n"
                "MOV     R2, #0x40\n"
                "STMEA   SP, {R2,R3}\n"
                "B       loc_FFE45A70\n"
"loc_FFE45A60:\n"
                "MOV     R1, #0x358\n"
                "LDR     R0, =0xFFE45748\n"
                "ADD     R1, R1, #2\n"
                "BL      sub_FFECA7B0\n"
"loc_FFE45A70:\n"
                "LDR     R2, =0x74A88\n"
                "ADD     R3, R8, R5\n"
                "LDMFD   SP, {R0,R12}\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "MOV     R3, R3,LSL#2\n"
                "ADD     R1, R2, #0x48\n"
                "ADD     R2, R2, #0x44\n"
                "STR     R0, [R1,R3]\n"
                "STR     R12, [R2,R3]\n"
                "MOV     R0, #1\n"
"loc_FFE45A98:\n"
                "ADD     SP, SP, #8\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
 );
}
