#include "stubs_asm.h"

NHSTUB(Close,0xFFE46B58)  
NHSTUB(Read, 0xFFE46BEC) 
NHSTUB(Remove, 0xFFE46B78) 
NHSTUB(Write, 0xFFE46BF8)
NHSTUB(DisplayImagePhysicalScreen, 0xFFDDBEEC)
NHSTUB(free, 0xFFCD9B84)
NHSTUB(kbd_read_keys_r2, 0xFFDE74F0)
NHSTUB(Mount_FileSystem, 0xFFE45E7C)
NHSTUB(kbd_pwr_off, 0xFFDE7BD4)
NHSTUB(SetPropertyCase, 0xFFC0BB5C)
NHSTUB(SetZoomActuatorSpeedPercent, 0xFFD670E8)  //null stub
