#include "stubs_asm.h"

DEF(physw_status, 0x54648)
DEF(physw_run, 0x7E10)

DEF(zoom_busy, 0x7E12C)
DEF(focus_busy, 0x7D860)

DEF(FlashParamsTable,0xFFEE8478)
DEF(canon_menu_active,0x2F38)
DEF(canon_shoot_menu_active,0x27B1)
DEF(recreview_hold, 0x2584)

DEF(movie_status, 0xA30C8)  
DEF(some_flag_for_af_scan, 0xC2F8)
DEF(zoom_status, 0x264C)
DEF(some_f_for_dng, 0x674C) 
DEF(second_ext_for_dng, 0x6770)
DEF(levent_table,0xFFED9260)
DEF(playrec_mode,0xC610)
