void __attribute__((naked,noinline)) init_file_modules_task(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "BL      _Unmount_FileSystem\n" // + 
                "BL      sub_FFED4544\n"
                "SUBS    R4, R0, #0\n"
                "MOV     R0, #0x5000\n"
                "MOV     R1, #0\n"
                "ADD     R0, R0, #6\n"
                "BEQ     loc_FFD9114C\n"
                "BL      sub_FFD63E6C\n"
"loc_FFD9114C:\n"
                "BL      sub_FFED4570_my\n"  //-------------->
                "MOV     R0, #0x5000\n"
                "CMP     R4, #0\n"
                "MOV     R1, R4\n"
                "ADD     R0, R0, #6\n"
                "LDMNEFD SP!, {R4,PC}\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFD63E6C\n"
 );
}

void __attribute__((naked,noinline)) sub_FFED4570_my(){
 asm volatile(
                "STR     LR, [SP,#-4]!\n"
                "BL      Mount_FileSystem_my\n" //-------------->
                "LDR     R3, =0xAE28\n"
                "LDR     R2, [R3]\n"
                "CMP     R2, #0\n"
                "BNE     loc_FFED45AC\n"
                "BL      sub_FFDB6100\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFC23BDC\n"
                "BL      sub_FFDB6100\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFC557D0\n"
                "BL      sub_FFDB6110\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFC23CB0\n"
"loc_FFED45AC:\n"
                "LDR     R2, =0xAE24\n"
                "MOV     R3, #1\n"
                "STR     R3, [R2]\n"
                "LDR     PC, [SP],#4\n"
 );
}

void __attribute__((naked,noinline)) Mount_FileSystem_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "MOV     R5, #0\n"
                "LDR     R6, =0x2C398\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC601F8\n"
                "LDR     R0, [R6,#0x38]\n"
                "BL      sub_FFC5F8B8\n"
                "SUBS    R1, R0, #0\n"
                "MOV     R0, R5\n"
                "BNE     loc_FFC60850\n"
                "LDR     R3, =0x2758\n"
                "LDR     R2, =0x2750\n"
                "STR     R1, [R3]\n"
                "LDR     R3, =0x2754\n"
                "STR     R1, [R2]\n"
                "STR     R1, [R3]\n"
"loc_FFC60850:\n"
                "BL      sub_FFC60248\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC60570_my\n" //--------------->
                "MOV     R4, R0\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC605F8\n"
                "AND     R4, R4, R0\n"
                "MOV     R2, R4\n"
                "MOV     R0, R6\n"
                "LDR     R1, [R6,#0x3C]\n"
                "BL      sub_FFC607C0\n"
                "STR     R0, [R6,#0x40]\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFC60570_my(){
 asm volatile(
                "STMFD   SP!, {R4-R7,LR}\n"
                "LDR     R7, =0x2754\n"
                "LDR     R3, [R7]\n"
                "MOV     R4, R0\n"
                "CMP     R3, #0\n"
                "ADD     R3, R4, R4,LSL#1\n"
                "RSB     R3, R4, R3,LSL#3\n"
                "LDR     R6, =0x2C3D0\n"
                "MOV     R5, R3,LSL#2\n"
                "MOV     R1, R4\n"
                "BNE     loc_FFC605E4\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFC60304_my\n"  //-------------->
                "SUBS    R3, R0, #0\n"
                "MOV     R1, R4\n"
                "BEQ     loc_FFC605BC\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFC60450\n"
                "MOV     R3, R0\n"
"loc_FFC605BC:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R4\n"
                "BEQ     loc_FFC605D0\n"
                "BL      sub_FFC5F990\n"
                "MOV     R3, R0\n"
"loc_FFC605D0:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R3\n"
                "MOVNE   R3, #1\n"
                "STRNE   R3, [R7]\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
"loc_FFC605E4:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFC60304_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R5, R1\n"
                "MOV     R8, R5,LSL#1\n"
                "ADD     R3, R8, R5\n"
                "LDR     R2, =0x2C3D4\n"
                "SUB     SP, SP, #8\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "LDR     R1, [R2,R3,LSL#2]\n"
                "MOV     R6, #0\n"
                "STR     R6, [SP]\n"
                "MOV     R7, R0\n"
                "STR     R6, [SP,#4]\n"
                "CMP     R1, #5\n"
                "LDRLS   PC, [PC,R1,LSL#2]\n"
                "B       loc_FFC60400\n"
                ".long loc_FFC603A4\n"
                ".long loc_FFC60358\n"
                ".long loc_FFC60358\n"
                ".long loc_FFC60358\n"
                ".long loc_FFC60358\n"
                ".long loc_FFC603F0\n"
"loc_FFC60358:\n"
                "MOV     R0, #3\n"
                "MOV     R1, #0x200\n"
                "MOV     R2, #0\n"
                "BL      sub_FFC02834\n"
                "SUBS    R6, R0, #0\n"
                "BEQ     loc_FFC60434\n"
                "ADD     R12, R8, R5\n"
                "RSB     R12, R5, R12,LSL#3\n"
                "LDR     R4, =0x2C3E4\n"
                "MOV     R0, R7\n"
                "MOV     R1, #0\n"
                "MOV     R2, #1\n"
                "MOV     R3, R6\n"
                "MOV     LR, PC\n"
                "LDR     PC, [R4,R12,LSL#2]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC603AC\n"
                "MOV     R0, #3\n"
                "BL      sub_FFC02904\n"
"loc_FFC603A4:\n"
                "MOV     R0, #0\n"
                "B       loc_FFC60434\n"
"loc_FFC603AC:\n"
                "MOV     R0, R7\n"
                "BL      sub_FFC70C80\n"
                "MOV     R1, R0\n"
                "ADD     R2, SP, #4\n"
                "MOV     R3, SP\n"
                "MOV     R0, R6\n"

                "STMFD   SP!, {R4-R11,LR}\n" // +
                "BL      mbr_read\n"    //-----------> 
                "LDMFD   SP!, {R4-R11,LR}\n" // +

          //    "BL      sub_FFC5FA94\n"  // original function
                "MOV     R4, R0\n"
                "MOV     R0, #3\n"
                "BL      sub_FFC02904\n"
                "CMP     R4, #0\n"
                "BNE     loc_FFC6040C\n"
                "MOV     R0, R7\n"
                "STR     R4, [SP,#4]\n"
                "BL      sub_FFC70C80\n"
                "STR     R0, [SP]\n"
                "B       loc_FFC6040C\n"
"loc_FFC603F0:\n"
                "MOV     R3, #0\n"
                "MOV     R2, #0x40\n"
                "STMEA   SP, {R2,R3}\n"
                "B       loc_FFC6040C\n"
"loc_FFC60400:\n"
                "LDR     R0, =0xFFC600EC\n"
                "MOV     R1, #0x2B4\n"
                "BL      sub_FFC03CF8\n"
"loc_FFC6040C:\n"
                "LDR     R2, =0x2C398\n"
                "ADD     R3, R8, R5\n"
                "LDMFD   SP, {R0,R12}\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "MOV     R3, R3,LSL#2\n"
                "ADD     R1, R2, #0x48\n"
                "ADD     R2, R2, #0x44\n"
                "STR     R0, [R1,R3]\n"
                "STR     R12, [R2,R3]\n"
                "MOV     R0, #1\n"
"loc_FFC60434:\n"
                "ADD     SP, SP, #8\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
 );
}
