#include "stubs_asm.h"

//NHSTUB(VbattGet, 0xFFC1C6D0)
//NHSTUB(GetZoomLensCurrentPosition, 0xFFE8793C)
//NHSTUB(GetZoomLensCurrentPoint, 0xFFE87928)
//NHSTUB(GetFocusLensSubjectDistance, 0xFFE9B4FC)

NHSTUB(malloc, 0xFFEF3278)
NHSTUB(free, 0xFFEF3284)

//NHSTUB(AllocateMemory, 0xFFC01AB0)
//NHSTUB(FreeMemory, 0xFFC01ABC)
//NHSTUB(isalpha, 0xFFEE7634)
//NHSTUB(isdigit, 0xFFEE7664)
//NHSTUB(islower, 0xFFEE7694)
//NHSTUB(isspace, 0xFFEE76DC)
//NHSTUB(isupper, 0xFFEE76F4)
//NHSTUB(CreatePhysicalVram, 0xFFD2E820)
//NHSTUB(DisplayPhysicalScreen, 0xFFD2EA78)
//NHSTUB(SetPropertyCase, 0xFFC14C94)
//NHSTUB(GetPropertyCase, 0xFFC14DE4)
//NHSTUB(GetSystemTime, 0xFFC04D38)
//NHSTUB(PhySw_testgpio, 0xFFC18964)
//NHSTUB(RefreshPhysicalScreen, 0xFFD7F49C)
//NHSTUB(kbd_pwr_off, 0xFFC188F0)
//NHSTUB(kbd_pwr_on, 0xFFC188C8)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFFD2CF98)  //null stub
NHSTUB(GetDrive_ClusterSize, 0xffc60cd4)
NHSTUB(GetDrive_TotalClusters, 0xffc60d10)
NHSTUB(GetDrive_FreeClusters, 0xffc60d4c)
