#include "stubs_asm.h"

NHSTUB(Fclose_Fut, 0xFFC5B5E0)
NHSTUB(Fopen_Fut, 0xFFC5B5A0)
NHSTUB(Fread_Fut, 0xFFC5B69C)
NHSTUB(Fseek_Fut, 0xFFC5B790)
NHSTUB(Fwrite_Fut, 0xFFC5B6F0)
NHSTUB(Feof_Fut, 0xFFC5B7DC)
NHSTUB(DeleteFile_Fut, 0xFFC5B46C)

NHSTUB(malloc, 0xFFEFD1A0)
NHSTUB(free, 0xFFEFD1AC)

//NHSTUB(VbattGet, 0xFFC1CD70)
//NHSTUB(GetZoomLensCurrentPosition, 0xFFE912B4)
//NHSTUB(GetZoomLensCurrentPoint, 0xFFE912A0)
//NHSTUB(GetFocusLensSubjectDistance, 0xFFEA4E74)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFFEBDC9C)  //null stub
