#include "stubs_asm.h"

NHSTUB(VbattGet, 0xFFC1C014)//ok
NHSTUB(SetZoomActuatorSpeedPercent, 0xFFE7D824) //ok
NHSTUB(free, 0xFFEE0F70)//ok  


NHSTUB(StartISDrive, 0xFFEA70CC) //not found
NHSTUB(StopISDrive, 0xFFEA70F0) //not found


NHSTUB(GetDrive_ClusterSize, 0xFFC5DC9C) //ok
NHSTUB(GetDrive_TotalClusters, 0xFFC5DCD8) //ok 
NHSTUB(GetDrive_FreeClusters, 0xFFC5DD14) // ok

NHSTUB(WriteSDCard, 0xFFC6D0E0)//












