
NSTUB(eventproc_export_memShow, 0xffc00bd0)

NSTUB(eventproc_export_CreateCountingSemaphore, 0xffc0b670)
NSTUB(eventproc_export_DeleteSemaphore, 0xffc0b6c8)

NSTUB(eventproc_export_TakeSemaphore, 0xffc0b774)
NSTUB(eventproc_export_GiveSemaphore, 0xffc0b844)

NSTUB(eventproc_export_CreateTask, 0xffc0b8e0)

NSTUB(eventproc_export_ExitTask, 0xffc0bb70)

NSTUB(eventproc_export_RotateConsoleZOder, 0xffc0c4c0)

NSTUB(eventproc_export_CPrintf, 0xffc0c6d0)
NSTUB(eventproc_export_CPutChar, 0xffc0c72c)
NSTUB(eventproc_export_GetCh, 0xffc0c758)
NSTUB(eventproc_export_GetStringWithPrompt, 0xffc0c7a8)
NSTUB(eventproc_export_OpenConsole, 0xffc0c808)
NSTUB(eventproc_export_CloseConsole, 0xffc0c96c)

NSTUB(eventproc_export_StartRedirectUART, 0xffc0d04c)
NSTUB(eventproc_export_StopRedirectUART, 0xffc0d164)

NSTUB(eventproc_export_sprintf, 0xffc0d7c8)

NSTUB(eventproc_export_strcpy, 0xffc0d88c)
NSTUB(eventproc_export_strcmp, 0xffc0d8a4)
NSTUB(eventproc_export_strlen, 0xffc0d8e8)
NSTUB(eventproc_export_memcmp, 0xffc0d90c)

NSTUB(eventproc_export_Fopen_Fut, 0xffc13544)
NSTUB(eventproc_export_Fclose_Fut, 0xffc13584)
NSTUB(eventproc_export_Fread_Fut, 0xffc13630)
NSTUB(eventproc_export_Fwrite_Fut, 0xffc13684)

NSTUB(eventproc_export_Fseek_Fut, 0xffc13724)

NSTUB(eventproc_export_Open, 0xffc13b34)
NSTUB(eventproc_export_Close, 0xffc13b5c)

NSTUB(eventproc_export_Read, 0xffc13c04)
NSTUB(eventproc_export_Write, 0xffc13c08)

NSTUB(eventproc_export_Lseek, 0xffc13d64)

NSTUB(eventproc_export_StartCameraLog, 0xffc1422c)
NSTUB(eventproc_export_ShowCameraLog, 0xffc14230)
NSTUB(eventproc_export_ShowCameraLogInfo, 0xffc14234)
NSTUB(eventproc_export_StopCameraLog, 0xffc14238)
NSTUB(eventproc_export_PutsCameraLogEvent, 0xffc1423c)

NSTUB(eventproc_export_NewTaskShell, 0xffc142bc)

NSTUB(eventproc_export_ExMem, 0xffc142d4)

NSTUB(eventproc_export_SleepTask, 0xffc17c9c)

NSTUB(eventproc_export_EraseLogSector, 0xffc4e4f8)

NSTUB(eventproc_export_UnLoadScript, 0xffc50b5c)

NSTUB(eventproc_export_LoadScript, 0xffc50c10)

NSTUB(eventproc_export_OpLog_Stop, 0xffc54d94)
NSTUB(eventproc_export_OpLog_ReadFromROM, 0xffc54dc0)
NSTUB(eventproc_export_OpLog_ReadFromSD, 0xffc54e40)
NSTUB(eventproc_export_OpLog_WriteToSD, 0xffc551e8)
NSTUB(eventproc_export_OpLog_WriteToROM, 0xffc555f0)
NSTUB(eventproc_export_OpLog_Get, 0xffc55618)
NSTUB(eventproc_export_OpLog_Show, 0xffc55638)
NSTUB(eventproc_export_OpLog_Play, 0xffc556d4)

NSTUB(eventproc_export_OpLog_Start, 0xffc55808)

NSTUB(eventproc_export_StartWDT, 0xffc56130)
NSTUB(eventproc_export_StopWDT, 0xffc56194)

NSTUB(eventproc_export_GetBuildDate, 0xffc56284)
NSTUB(eventproc_export_GetBuildTime, 0xffc5628c)
NSTUB(eventproc_export_GetFirmwareVersion, 0xffc56294)

NSTUB(eventproc_export_CheckSumAll, 0xffc563a0)
NSTUB(eventproc_export_RomCheckSum, 0xffc56590)

NSTUB(eventproc_export_FmtMenu_ExecuteQuickFormat, 0xffc59c54)

NSTUB(eventproc_export_CreateController, 0xffc5a938)
NSTUB(eventproc_export_DeleteController, 0xffc5a9f4)

NSTUB(eventproc_export_MoveControllerToTopOfZOrder, 0xffc5ab78)

NSTUB(eventproc_export_GetSelfControllerHandle, 0xffc5acbc)

NSTUB(eventproc_export_PostLogicalEventForNotPowerType, 0xffc5b0f4)
NSTUB(eventproc_export_PostLogicalEventToUI, 0xffc5b140)
NSTUB(eventproc_export_PostEventShootSeqToUI, 0xffc5b1b8)
NSTUB(eventproc_export_ShowLogicalEventName, 0xffc5b20c)

NSTUB(eventproc_export_IsControlEventActive, 0xffc5b7b0)

NSTUB(eventproc_export_SetScriptMode, 0xffc5b870)

NSTUB(eventproc_export_UiEvnt_StartDisguiseCradleStatus, 0xffc5b898)

NSTUB(eventproc_export_UnlockMainPower, 0xffc5b9d8)
NSTUB(eventproc_export_LockMainPower, 0xffc5ba84)
NSTUB(eventproc_export_SetAutoShutdownTime, 0xffc5baf8)

NSTUB(eventproc_export_HardwareDefectWithRestart, 0xffc5bcd0)
NSTUB(eventproc_export_HardwareDefect, 0xffc5bd20)

NSTUB(eventproc_export_PTM_AllResetToFactorySetting, 0xffc5bf34)
NSTUB(eventproc_export_PTM_AllReset, 0xffc5bf44)

NSTUB(eventproc_export_PTM_SetCurrentCaptureMode, 0xffc5c2ac)

NSTUB(eventproc_export_PTM_GetWorkingCaptureMode, 0xffc5c3c4)
NSTUB(eventproc_export_PTM_SetCurrentItem, 0xffc5c3c8)

NSTUB(eventproc_export_PTM_GetCurrentItem, 0xffc5c3d4)

NSTUB(eventproc_export_PTM_NextItem, 0xffc5c440)
NSTUB(eventproc_export_PTM_PrevItem, 0xffc5c444)

NSTUB(eventproc_export_PTM_IsEnableItem, 0xffc5c454)
NSTUB(eventproc_export_PTM_SetProprietyEnable, 0xffc5c458)

NSTUB(eventproc_export_PTM_BackupUIProperty, 0xffc5c470)
NSTUB(eventproc_export_PTM_RestoreUIProperty, 0xffc5c474)

NSTUB(eventproc_export_SetCurrentCaptureModeType, 0xffc61d9c)
NSTUB(eventproc_export_GetCurrentCaptureModeType, 0xffc61dd8)

NSTUB(eventproc_export_StartGUISystem, 0xffc6e854)

NSTUB(eventproc_export_atol, 0xffc6e994)

NSTUB(eventproc_export_memcpy, 0xffc6ebb4)

NSTUB(eventproc_export_SetSDPwrPort, 0xffd0a024)
NSTUB(eventproc_export_GetAdVBattBottom, 0xffd0a050)
NSTUB(eventproc_export_GetAdChValue, 0xffd0a054)
NSTUB(eventproc_export_BeepDrive, 0xffd0a058)
NSTUB(eventproc_export_VbattGet, 0xffd0a05c)
NSTUB(eventproc_export_LEDDrive, 0xffd0a060)
NSTUB(eventproc_export_ShowPhySwStatus, 0xffd0a064)
NSTUB(eventproc_export_SetRawSWCheckMode, 0xffd0a074)
NSTUB(eventproc_export_OnPrintPhySw, 0xffd0a084)
NSTUB(eventproc_export_OffPrintPhySw, 0xffd0a094)
NSTUB(eventproc_export_GetSwitchStatus, 0xffd0a0a4)
NSTUB(eventproc_export_ShowSDStatus, 0xffd0a0a8)
NSTUB(eventproc_export_GetSDDetect, 0xffd0a0b8)
NSTUB(eventproc_export_GetSDProtect, 0xffd0a0bc)
NSTUB(eventproc_export_SetIgnoreAVJACK, 0xffd0a0c0)
NSTUB(eventproc_export_GetDialEventId, 0xffd0a0d0)

NSTUB(eventproc_export_MonSelEvent, 0xffd0a2e8)
NSTUB(eventproc_export_MemoryChecker, 0xffd0a2ec)
NSTUB(eventproc_export_VerifyByte, 0xffd0a2f0)
NSTUB(eventproc_export_EraseSignature, 0xffd0a2f4)
NSTUB(eventproc_export_SDump, 0xffd0a304)
NSTUB(eventproc_export_Dump, 0xffd0a308)
NSTUB(eventproc_export_Dump32, 0xffd0a318)
NSTUB(eventproc_export_Poke32, 0xffd0a32c)
NSTUB(eventproc_export_Poke16, 0xffd0a33c)
NSTUB(eventproc_export_Poke8, 0xffd0a34c)
NSTUB(eventproc_export_Peek32, 0xffd0a35c)
NSTUB(eventproc_export_Peek16, 0xffd0a360)
NSTUB(eventproc_export_Peek8, 0xffd0a364)
NSTUB(eventproc_export_Wait, 0xffd0a368)

NSTUB(eventproc_export_ShowAllTaskInfo, 0xffd0a37c)

NSTUB(eventproc_export_UI_ShowStateOfRecMode, 0xffd0ac64)

NSTUB(eventproc_export_UIFS_SetDialStillRec, 0xffd0ad64)
NSTUB(eventproc_export_UIFS_SetDialMovieRec, 0xffd0ad8c)
NSTUB(eventproc_export_UIFS_SetDialPlay, 0xffd0adb4)
NSTUB(eventproc_export_UIFS_OpenPopupStrobe, 0xffd0addc)
NSTUB(eventproc_export_UIFS_ClosePopupStrobe, 0xffd0ae0c)
NSTUB(eventproc_export_UIFS_MountExtFlash, 0xffd0ae3c)
NSTUB(eventproc_export_UIFS_UnmountExtFlash, 0xffd0ae6c)
NSTUB(eventproc_export_UIFS_PressTeleButton, 0xffd0ae9c)
NSTUB(eventproc_export_UIFS_UnpressTeleButton, 0xffd0aed8)
NSTUB(eventproc_export_UIFS_PressWideButton, 0xffd0af10)
NSTUB(eventproc_export_UIFS_UnpressWideButton, 0xffd0af4c)
NSTUB(eventproc_export_UIFS_ConnectVideo, 0xffd0af84)
NSTUB(eventproc_export_UIFS_DisconnectVideo, 0xffd0afb4)
NSTUB(eventproc_export_UIFS_MoveZoomTo, 0xffd0afe4)
NSTUB(eventproc_export_UIFS_StopPostingUIEvent, 0xffd0afe8)
NSTUB(eventproc_export_UIFS_RestartPostingUIEvent, 0xffd0afec)
NSTUB(eventproc_export_UIFS_SetCaptureModeToP, 0xffd0aff0)
NSTUB(eventproc_export_UIFS_SetCaptureModeToTv, 0xffd0b024)
NSTUB(eventproc_export_UIFS_SetCaptureModeToM, 0xffd0b058)
NSTUB(eventproc_export_UIFS_SetCaptureModeToMacro, 0xffd0b08c)
NSTUB(eventproc_export_UIFS_SetCaptureModeToISO3200, 0xffd0b094)
NSTUB(eventproc_export_UIFS_Capture, 0xffd0b09c)
NSTUB(eventproc_export_UIFS_CaptureNoneStop, 0xffd0b0a0)
NSTUB(eventproc_export_UIFS_StartMovieRecord, 0xffd0b0a4)
NSTUB(eventproc_export_UIFS_StopMovieRecord, 0xffd0b0a8)
NSTUB(eventproc_export_UIFS_StartClockMode, 0xffd0b0ac)
NSTUB(eventproc_export_UIFS_EndClockMode, 0xffd0b0b4)
NSTUB(eventproc_export_UIFS_SetCradleSetting, 0xffd0b0bc)
NSTUB(eventproc_export_UIFS_WriteFirmInfoToFile, 0xffd0b0c0)
NSTUB(eventproc_export_UIFS_GetMovieRecoadableNumber, 0xffd0b0c4)
NSTUB(eventproc_export_UIFS_GetStillShotableNumber, 0xffd0b10c)

NSTUB(eventproc_export_WriteToRom, 0xffd11be4)
NSTUB(eventproc_export_EraseSectorOfRom, 0xffd11c94)

NSTUB(eventproc_export_GetTimeOfSystem, 0xffd15bb8)

NSTUB(eventproc_export_ExecuteResetFactoryWithRomWrite, 0xffd2aa54)

NSTUB(eventproc_export_memset, 0xffd67c50)

NSTUB(eventproc_export_sscanf, 0xffd68194)

NSTUB(eventproc_export_AdditionAgentRAM, 0xffddba40)

NSTUB(eventproc_export_StartDirectTransferManager, 0xffdef984)

NSTUB(eventproc_export_StoptDtConfirmMenu, 0xffdf0508)

NSTUB(eventproc_export_StartDtConfirmMenu, 0xffdf0650)

NSTUB(eventproc_export_StoptDtExecuteMenu, 0xffe44db8)

NSTUB(eventproc_export_StartDtExecuteMenu, 0xffe45144)

