#include "stubs_asm.h"

NHSTUB(Close,0xFFE46BCC)
NHSTUB(Read,0xFFE46C60) 
NHSTUB(Remove,0xFFE46BEC)
NHSTUB(Write,0xFFE46C6C)
NHSTUB(DisplayImagePhysicalScreen ,0xFFDDBF60) 
NHSTUB(free,0xFFCD9B84) 
NHSTUB(kbd_read_keys_r2  ,0xFFDE7564) 
NHSTUB(Mount_FileSystem ,0xFFE45EF0) 
NHSTUB(kbd_pwr_off, 0xFFDE7C48)
NHSTUB(SetZoomActuatorSpeedPercent, 0xFFD670E8)
NHSTUB(SetPropertyCase,0xFFC0BB5C)
NHSTUB(GetDrive_ClusterSize, 0xFFE463B8)
NHSTUB(GetDrive_TotalClusters, 0xFFE463F4)
NHSTUB(GetDrive_FreeClusters, 0xFFE46430)
NHSTUB(WriteSDCard, 0xFFE58F60)

