#include "stubs_asm.h"

// Found in sub_FF821764
DEF(physw_run, 0x1C24 + 0x0C)

// Found @ ROM:FF821804
DEF(physw_status, 0x12DA4)

// Found in sub_FFA3014
DEF(FlashParamsTable,0xFFBBB2A4) 

// Found in sub_FF84C9D0
DEF(led_table, 0x2644 + 0x04)

// Found in sub_FF954098
DEF(zoom_busy, 0x9ACC + 0x1C)

// Found in sub_FF94CD34
DEF(focus_busy, 0x996C + 0x08)

// Found in sub_FF98FEE4 
DEF(recreview_hold, 0xB31C + 0xE4)

// Found in sub_FF9A661C
DEF(canon_shoot_menu_active, 0xB818 + 1)

// Found in sub_FF87E5E0
DEF(canon_menu_active, 0x5A58 + 4)

// Found in sub_FF866ECC
DEF(movie_status, 0x5570 + 0x38)

// Found in sub_FF8716D4
DEF(playrec_mode, 0x57C0+0x4)

// Found in sub_FF9FA6A8
DEF(enabled_refresh_physical_screen, 0xCABC+0x34)

// Found @ several entries in "Zoom/Lens Section" ROM:FFAA4CEC
DEF(zoom_status, 0xF2A0)




