#include "stubs_asm.h"

DEF(physw_status, 0x10610)
DEF(physw_run, 0x1BF4 + 0xC)
DEF(playrec_mode, 0x5558 + 0x4)

DEF(zoom_busy, 0x8A74 + 0x14)
DEF(focus_busy, 0x898C + 0x8)
DEF(FlashParamsTable, 0xFFAF8034)
DEF(canon_menu_active, 0x99E4 + 4)
DEF(canon_shoot_menu_active, 0x9FCC + 1)
DEF(recreview_hold, 0x9CF8 + 0xAC)
DEF(movie_status, 0x5390 + 0x3C)
DEF(some_flag_for_af_scan, 0xD1F8)
DEF(zoom_status, 0xD474)
DEF(levent_table,0xFFAD2CE8)
