#include "stubs_asm.h"
DEF(zoom_busy, 0x7a00+0x14) //S90 @FF95D6D0 (possible)          
DEF(focus_busy, 0x78d4 + 8)    //S90 @FF957BE0
DEF(zoom_status, 0x8AA4) //S90                 
DEF(canon_menu_active, 0x3034 + 4)  //S90 @0xFF88D65C      
DEF(movie_status, 0x7ab0 + 0x38) //S90 @FF961124        
DEF(enabled_refresh_physical_screen, 0xa36c) //S90 @FFA07DB4
DEF(playrec_mode, 0x2d60+0x4)  // S90@FF87FD20
DEF(FlashParamsTable,0xFFBEFBC4) // S90 Ref @FFAAE8F0
DEF(physw_status, 0x330d8)                 
DEF(physw_run, 0x1C38 + 0x0C)            
DEF(led_table, 0x2538 + 0x04) //S90 @FF85D24C
DEF(some_flag_for_af_scan, 0x7FF4)	 // S90 @0xFF96452C   
DEF(enabled_refresh_physical_screen, 0xA36C) //S90 at FFA07D50
DEF(canon_shoot_menu_active, 0x8DD0 + 1)  //S90 @FF9AB530
DEF(levent_table,0xFFB8B4C4) //S90 @0xFFB8B4C4
DEF(recreview_hold, 0x8944+0xE4)  //S90@0xFF99693C 




