void __attribute__((naked,noinline)) init_file_modules_task(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "BL      _Unmount_FileSystem\n" // + 
                "BL      sub_FF81CA18\n"
                "SUBS    R4, R0, #0\n"
                "MOV     R0, #0x5000\n"
                "MOV     R1, #0\n"
                "ADD     R0, R0, #6\n"
                "BEQ     loc_FF824454\n"
                "BL      sub_FFB5F514\n"
"loc_FF824454:\n"
                "BL      sub_FF81CA44_my\n"  //------------->
                "MOV     R0, #0x5000\n"
                "CMP     R4, #0\n"
                "MOV     R1, R4\n"
                "ADD     R0, R0, #6\n"
                "LDMNEFD SP!, {R4,PC}\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFB5F514\n"
 );
}

void __attribute__((naked,noinline)) sub_FF81CA44_my(){
 asm volatile(
                "STR     LR, [SP,#-4]!\n"
                "BL      Mount_FileSystem_my\n"  //-------------->
                "LDR     R3, =0x1E0C\n"
                "LDR     R2, [R3]\n"
                "CMP     R2, #0\n"
                "BNE     loc_FF81CA80\n"
                "BL      sub_FF848778\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFA7D434\n"
                "BL      sub_FF848778\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFA939CC\n"
                "BL      sub_FF848788\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFA7D524\n"
"loc_FF81CA80:\n"
                "LDR     R2, =0x1E08\n"
                "MOV     R3, #1\n"
                "STR     R3, [R2]\n"
                "LDR     PC, [SP],#4\n"
 );
}

void __attribute__((naked,noinline)) Mount_FileSystem_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "MOV     R4, #0\n"
                "MOV     R5, R4\n"
                "LDR     R6, =0x85C60\n"
                "MOV     R0, R5\n"
                "BL      sub_FFAAD95C\n"
                "LDR     R0, [R6,#0x38]\n"
                "BL      sub_FFAACFF0\n"
                "CMP     R0, R4\n"
                "MOV     R1, R5\n"
                "MOV     R0, R5\n"
                "BNE     loc_FFAADFC8\n"
                "LDR     R3, =0xA320\n"
                "LDR     R2, =0xA318\n"
                "STR     R1, [R3]\n"
                "LDR     R3, =0xA31C\n"
                "STR     R1, [R2]\n"
                "STR     R1, [R3]\n"
"loc_FFAADFC8:\n"
                "BL      sub_FFAAD9AC\n"
                "MOV     R0, R5\n"
                "BL      sub_FFAADCDC_my\n"  //--------------->
                "MOV     R4, R0\n"
                "MOV     R0, R5\n"
                "BL      sub_FFAADD64\n"
                "LDR     R1, [R6,#0x3C]\n"
                "AND     R2, R4, R0\n"
                "MOV     R0, R6\n"
                "BL      sub_FFAADF30\n"
                "STR     R0, [R6,#0x40]\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFAADCDC_my(){
 asm volatile(
                "STMFD   SP!, {R4-R7,LR}\n"
                "LDR     R7, =0xA31C\n"
                "LDR     R3, [R7]\n"
                "MOV     R4, R0\n"
                "CMP     R3, #0\n"
                "ADD     R3, R4, R4,LSL#1\n"
                "RSB     R3, R4, R3,LSL#3\n"
                "LDR     R6, =0x85C98\n"
                "MOV     R5, R3,LSL#2\n"
                "MOV     R1, R4\n"
                "BNE     loc_FFAADD50\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFAADA64_my\n"  //--------------->
                "SUBS    R3, R0, #0\n"
                "MOV     R1, R4\n"
                "BEQ     loc_FFAADD28\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFAADBB8\n"
                "MOV     R3, R0\n"
"loc_FFAADD28:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R4\n"
                "BEQ     loc_FFAADD3C\n"
                "BL      sub_FFAAD0C8\n"
                "MOV     R3, R0\n"
"loc_FFAADD3C:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R3\n"
                "MOVNE   R3, #1\n"
                "STRNE   R3, [R7]\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
"loc_FFAADD50:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFAADA64_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R5, R1\n"
                "MOV     R8, R5,LSL#1\n"
                "ADD     R3, R8, R5\n"
                "LDR     R2, =0x85C9C\n"
                "SUB     SP, SP, #8\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "LDR     R1, [R2,R3,LSL#2]\n"
                "MOV     R6, #0\n"
                "STR     R6, [SP]\n"
                "MOV     R7, R0\n"
                "STR     R6, [SP,#4]\n"
                "CMP     R1, #6\n"
                "LDRLS   PC, [PC,R1,LSL#2]\n"
                "B       loc_FFAADB64\n"
                ".long loc_FFAADB08\n"
                ".long loc_FFAADABC\n"
                ".long loc_FFAADABC\n"
                ".long loc_FFAADABC\n"
                ".long loc_FFAADABC\n"
                ".long loc_FFAADB54\n"
                ".long loc_FFAADABC\n"
"loc_FFAADABC:\n"
                "MOV     R0, #3\n"
                "MOV     R1, #0x200\n"
                "MOV     R2, #0\n"
                "BL      sub_FF81E370\n"
                "SUBS    R6, R0, #0\n"
                "BEQ     loc_FFAADB9C\n"
                "ADD     R12, R8, R5\n"
                "RSB     R12, R5, R12,LSL#3\n"
                "LDR     R4, =0x85CAC\n"
                "MOV     R0, R7\n"
                "MOV     R1, #0\n"
                "MOV     R2, #1\n"
                "MOV     R3, R6\n"
                "MOV     LR, PC\n"
                "LDR     PC, [R4,R12,LSL#2]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFAADB10\n"
                "MOV     R0, #3\n"
                "BL      sub_FF81E440\n"
"loc_FFAADB08:\n"
                "MOV     R0, #0\n"
                "B       loc_FFAADB9C\n"
"loc_FFAADB10:\n"
                "MOV     R0, R7\n"
                "BL      sub_FFAC1550\n"
                "MOV     R1, R0\n"
                "ADD     R2, SP, #4\n"
                "MOV     R3, SP\n"
                "MOV     R0, R6\n"

                "STMFD   SP!, {R4-R11,LR}\n" // +
                "BL      mbr_read\n"    //-----------> 
                "LDMFD   SP!, {R4-R11,LR}\n" // +

          //    "BL      sub_FFAAD1F4\n"    // original function

                "MOV     R4, R0\n"
                "MOV     R0, #3\n"
                "BL      sub_FF81E440\n"
                "CMP     R4, #0\n"
                "BNE     loc_FFAADB74\n"
                "MOV     R0, R7\n"
                "STR     R4, [SP,#4]\n"
                "BL      sub_FFAC1550\n"
                "STR     R0, [SP]\n"
                "B       loc_FFAADB74\n"
"loc_FFAADB54:\n"
                "MOV     R3, #0\n"
                "MOV     R2, #0x40\n"
                "STMEA   SP, {R2,R3}\n"
                "B       loc_FFAADB74\n"
"loc_FFAADB64:\n"
                "MOV     R1, #0x358\n"
                "LDR     R0, =0xFFAAD84C\n"
                "ADD     R1, R1, #2\n"
                "BL      sub_FFB4D970\n"
"loc_FFAADB74:\n"
                "LDR     R2, =0x85C60\n"
                "ADD     R3, R8, R5\n"
                "LDMFD   SP, {R0,R12}\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "MOV     R3, R3,LSL#2\n"
                "ADD     R1, R2, #0x48\n"
                "ADD     R2, R2, #0x44\n"
                "STR     R0, [R1,R3]\n"
                "STR     R12, [R2,R3]\n"
                "MOV     R0, #1\n"
"loc_FFAADB9C:\n"
                "ADD     SP, SP, #8\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
 );
}
