#include "stubs_asm.h"

DEF(physw_status, 0x11EC4)
DEF(physw_run, 0x1C24 + 0x0C)
DEF(FlashParamsTable,0xFFB746CC)
DEF(zoom_busy, 0x90E4 + 0x1C)
DEF(focus_busy, 0x8F84 + 8)
DEF(canon_menu_active, 0x58D4 + 4)
DEF(canon_shoot_menu_active, 0xAC28 + 1)
DEF(recreview_hold, 0xA78C + 0xDC)
DEF(zoom_status, 0xE3EC) // sub_FFA7B2B8
DEF(movie_status, 0x53F8 + 0x38)
DEF(enabled_refresh_physical_screen, 0xBE84+0x34)
DEF(playrec_mode, 0x563C+0x4)
