#include "stubs_asm.h"

NHSTUB(UniqueLedOn, 0xFF82D048)
NHSTUB(UniqueLedOff, 0xFF82D08C)
NHSTUB(free, 0xFFAD6E2C)
NHSTUB(VbattGet, 0xFF82B704)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFF8117EC)

NHSTUB(kbd_p1_1, 0xFF82DB90)
NHSTUB(kbd_p1_2, 0xFF82DBC4)
NHSTUB(kbd_p1_3, 0xFF82DBF8)

NHSTUB(GetDrive_ClusterSize, 0xFF86DE24)
NHSTUB(GetDrive_TotalClusters, 0xFF86DE60)
NHSTUB(GetDrive_FreeClusters, 0xFF86DE9C)
NHSTUB(ExpCtrlTool_StopContiAE,  0xFF8F2DB0) 
NHSTUB(ExpCtrlTool_StartContiAE, 0xFF8F2D98) 
NHSTUB(MakeAFScan,  0xFF94E9AC) 

