#include "conf.h"

int *video_quality = &conf.video_quality;
int *video_mode    = &conf.video_mode;

long def_table1[9]={0x2000,0x38D,0x788,0x5800,0x9C5,0x14B8,0x10000,0x1C6A,0x3C45};
long def_table2[9]={0x1CCD,-0x2E1,-0x579,0x4F33,-0x7EB,-0xF0C,0xE666,-0x170A,-0x2BC6};

long table1[9], table2[9];

void change_video_tables(int a, int b){
 int i;
 for (i=0;i<9;i++) {table1[i]=(def_table1[i]*a)/b; table2[i]=(def_table2[i]*a)/b;}
}

long CompressionRateTable[]={0x60, 0x5D, 0x5A, 0x57, 0x54, 0x51, 0x4D, 0x48, 0x42, 0x3B, 0x32, 0x29, 0x22, 0x1D, 0x17, 0x14, 0x10, 0xE, 0xB, 9, 7, 6, 5, 4, 3, 2, 1};

void __attribute__((naked,noinline)) sub_FFD52C2C_my(){
 asm volatile(
                "CMP     R2, #1\n"          
                "STMFD   SP!, {R4-R7,LR}\n" 
                "MOV     R7, R0\n"          
                "MOV     R6, R1\n"          
                "MOVEQ   R3, #0x79\n"       
                "STREQ   R3, [R6]\n"        
                "LDMEQFD SP!, {R4-R7,PC}\n" 
                "LDR     R12, =0x71678\n"   
                "LDR     R0, [R12]\n"       
                "LDR     R3, =0x71680\n"    
                "CMP     R0, #0\n"          
                "LDR     R1, [R3]\n"        
                "BEQ     loc_FFD52C74\n"    
                "LDR     R2, =0x71684\n"    
                "LDR     R3, [R2]\n"        
                "CMP     R3, #1\n"          
                "BNE     loc_FFD52C88\n"    
                "B       loc_FFD52C78\n"    


"loc_FFD52C74:\n"                           
                "LDR     R2, =0x71684\n"    

"loc_FFD52C78:\n"                           
                "MOV     R3, #0\n"          
                "STR     R3, [R2]\n"        
                "STR     R7, [R12]\n"       
                "B       loc_FFD52D40\n"    


"loc_FFD52C88:\n"                           
                "LDR     R2, =0x7167C\n"    
                "LDR     R3, [R2]\n"        
                "LDR     R5, =table1\n"        //+ 0xFFD52A9C
                "ADD     R3, R3, R3,LSL#1\n" 
                "MOV     LR, R3,LSL#2\n"    
                "LDR     R2, [R5,LR]\n"     
                "LDR     R4, =table2\n"        //+ 0xFFD52AC0
                "RSB     R12, R2, R0\n"     
                "LDR     R3, [R4,LR]\n"     
                "CMP     R12, #0\n"         
                "RSB     R0, R3, R0\n"      
                "BLE     loc_FFD52CEC\n"    
                "ADD     R3, R5, #4\n"      
                "LDR     R2, [R3,LR]\n"     
                "CMP     R2, R12\n"         
                "ADDGE   R1, R1, #1\n"      
                "BGE     loc_FFD52CE0\n"    
                "ADD     R3, R5, #8\n"      
                "LDR     R2, [R3,LR]\n"     
                "CMP     R2, R12\n"         
                "ADDGE   R1, R1, #2\n"      
                "ADDLT   R1, R1, #3\n"      

"loc_FFD52CE0:\n"                           
//             "CMP     R1, #0xE\n"  //-      
//             "MOVGE   R1, #0xE\n"  //-      

                "CMP     R1, #0x1A\n"  //+      
                "MOVGE   R1, #0x1A\n"  //+      

                "B       loc_FFD52D24\n"    


"loc_FFD52CEC:\n"                           
                "CMP     R0, #0\n"          
                "BGE     loc_FFD52D24\n"    
                "ADD     R3, R4, #4\n"      
                "LDR     R2, [R3,LR]\n"     
                "CMP     R2, R0\n"          
                "SUBLE   R1, R1, #1\n"      
                "BLE     loc_FFD52D1C\n"    
                "ADD     R3, R4, #8\n"      
                "LDR     R2, [R3,LR]\n"     
                "CMP     R2, R0\n"          
                "SUBLE   R1, R1, #2\n"      
                "SUBGT   R1, R1, #3\n"      

"loc_FFD52D1C:\n"                           
                "CMP     R1, #0\n"          
                "MOVLT   R1, #0\n"          

"loc_FFD52D24:\n"                           
                                        
                "LDR     R0, =0x71680\n"    
                "LDR     R3, [R0]\n"        
                "CMP     R1, R3\n"          
                "LDRNE   R2, =0x71684\n"    
                "MOVNE   R3, #1\n"          
                "STRNE   R1, [R0]\n"        
                "STRNE   R3, [R2]\n"        

"loc_FFD52D40:\n"                           
                "LDR     R3, =0x71680\n"    
//              "LDR     R1, =0x61A4\n"    //- 
                "LDR     R1, =video_mode\n"  //+
                "LDR     R0, [R3]\n"        
                "LDR     R2, =CompressionRateTable\n" //+ 0xFFD52A60
                "LDR     R12, [R1]\n"                       
                "LDR     R12, [R12]\n"    //+
                "LDR     LR, [R2,R0,LSL#2]\n" 
                "LDR     R3, =0x71678\n"    
                "CMP     R12, #1\n"         
                "STR     R7, [R3]\n"        
                "STR     LR, [R6]\n"        
//              "MOVEQ   R3, #0xB\n"        
                "LDREQ   R3, =video_quality\n"   //+     
                "LDREQ   R3, [R3]\n"   //+     
                "LDREQ   R3, [R3]\n"   //+     
                "STREQ   R3, [R6]\n"        
                "BL      mute_on_zoom\n"     // +
                "LDMFD   SP!, {R4-R7,PC}\n" 

 );
}


void __attribute__((naked,noinline)) sub_FFD5383C_my(){
 asm volatile(
                "STMFD   SP!, {R4-R11,LR}\n" 
                "LDR     R5, =0x71914\n"    
                "SUB     SP, SP, #0x14\n"   
                "LDR     LR, [R5]\n"        
                "LDR     R12, =0x7192C\n"   
                "ADD     LR, LR, #1\n"      
                "LDR     R4, [R12]\n"       
                "STR     LR, [R5]\n"        
                "LDR     R12, =0x719AC\n"   
                "STR     R0, [SP,#0x10]\n"  
                "STR     R1, [SP,#0xC]\n"   
                "STR     R2, [SP,#8]\n"     
                "STR     R3, [SP,#4]\n"     
                "CMP     LR, R4\n"          
                "LDR     R11, [R12]\n"      
                "MOVHI   R0, #0x80000001\n"  // remove frame
                "BHI     loc_FFD53D24\n"     // (time) limit
                "LDR     R3, =0x71990\n"    
                "MOV     R0, LR\n"          
                "LDR     R1, [R3]\n"        
                "BL      sub_FFEF4D84\n"       
                "CMP     R0, #1\n"          
                "BNE     loc_FFD53A5C\n"    
                "LDR     R0, =0x719B4\n"    
                "LDR     R1, =0x71900\n"    
                "LDR     R3, [R0]\n"        
                "LDR     R2, [R1]\n"        
                "CMP     R3, R2\n"          
                "LDREQ   R3, =0x719B0\n"    
                "LDREQ   R5, [R3]\n"        
                "MOVNE   R5, R2\n"          
                "LDR     R3, =0x71914\n"    
                "LDR     R2, =0x71990\n"    
                "LDR     R0, [R3]\n"        
                "LDR     R1, [R2]\n"        
                "BL      sub_FFEF46F4\n"       
                "LDR     R3, =0x71908\n"    
                "ADD     R0, R0, #1\n"      
                "AND     R0, R0, #1\n"      
                "STR     R5, [R3,R0,LSL#2]\n" 
                "LDR     R3, =0x718FC\n"    
                "LDR     R2, [R3]\n"        
                "CMP     R5, R2\n"          
                "BHI     loc_FFD5390C\n"    
                "LDR     R4, =0x7194C\n"    
                "LDR     R3, [R4]\n"        
                "ADD     R3, R5, R3\n"      
                "ADD     R3, R3, #8\n"      
                "CMP     R2, R3\n"          
                "BCS     loc_FFD53910\n"    

"loc_FFD53904:\n"                            
                                        
                "MOV     R0, #0x80000003\n" 
                "B       loc_FFD53D24\n"    


"loc_FFD5390C:\n"                            
                "LDR     R4, =0x7194C\n"    

"loc_FFD53910:\n"                            
                "LDR     R3, [R4]\n"        
                "LDR     R2, =0x719B4\n"    
                "ADD     R1, R5, R3\n"      
                "LDR     R3, [R2]\n"        
                "ADD     R2, R1, #8\n"      
                "CMP     R2, R3\n"          
                "BLS     loc_FFD5395C\n"    
                "LDR     R2, =0x719B0\n"    
                "LDR     R0, =0x718FC\n"    
                "RSB     R3, R3, R1\n"      
                "LDR     R1, [R2]\n"        
                "ADD     R3, R3, #8\n"      
                "LDR     R2, [R0]\n"        
                "ADD     R1, R1, R3\n"      
                "CMP     R2, R1\n"          
                "BCC     loc_FFD53904\n"    
                "LDR     R3, =0x71900\n"    
                "STR     R1, [R3]\n"        
                "B       loc_FFD53964\n"    


"loc_FFD5395C:\n"                            
                "LDR     R3, =0x71900\n"    
                "STR     R2, [R3]\n"        

"loc_FFD53964:\n"                            
                "LDR     R3, [R4]\n"        
                "LDR     R12, =0x71960\n"   
                "ADD     R3, R3, #0x18\n"   
                "LDR     R2, [R12,#4]\n"    
                "MOV     R0, R3\n"          
                "MOV     R1, #0\n"          
                "CMP     R1, R2\n"          
                "BHI     loc_FFD53BA8\n"    
                "BNE     loc_FFD53994\n"    
                "LDR     R3, [R12]\n"       
                "CMP     R0, R3\n"          
                "BHI     loc_FFD53BA8\n"    

"loc_FFD53994:\n"                            
                "LDR     R4, [R4]\n"        
                "LDR     LR, =0x71968\n"    
                "STR     R4, [SP]\n"        
                "LDR     R12, =0x71960\n"   
                "LDR     R3, =0x71914\n"    
                "LDMIA   LR, {R7,R8}\n"     
                "LDMIA   R12, {R5,R6}\n"    
                "LDR     R10, [R3]\n"       
                "LDR     R2, =0x71990\n"    
                "MOV     R3, R4\n"          
                "MOV     R4, #0\n"          
                "ADDS    R7, R7, R3\n"      
                "ADC     R8, R8, R4\n"      
                "LDR     R9, [R2]\n"        
                "SUBS    R5, R5, R3\n"      
                "SBC     R6, R6, R4\n"      
                "MVN     R2, #0\n"          
                "MVN     R1, #0x17\n"       
                "ADDS    R5, R5, R1\n"      
                "MOV     R4, #0\n"          
                "MOV     R3, #0x18\n"       
                "ADC     R6, R6, R2\n"      
                "ADDS    R7, R7, R3\n"      
                "ADC     R8, R8, R4\n"      
                "STMIA   R12, {R5,R6}\n"    
                "SUB     R0, R10, #1\n"     
                "MOV     R1, R9\n"          
                "STMIA   LR, {R7,R8}\n"     
                "BL      sub_FFEF46F4\n"       
                "CMP     R10, #1\n"         
                "MLA     R0, R9, R0, R0\n"  
                "BEQ     loc_FFD53A5C\n"    
                "SUB     R3, R0, #1\n"      
                "MOV     R3, R3,LSL#4\n"    
                "ADD     R4, R11, #0x10\n"  
                "ADD     R5, R11, #0x14\n"  
                "LDR     R1, [R5,R3]\n"     
                "LDR     R2, [R4,R3]\n"     
                "LDR     LR, =0x62773130\n" 
                "ADD     R2, R2, R1\n"      
                "MOV     R3, R0,LSL#4\n"    
                "ADD     R2, R2, #8\n"      
                "MOV     R0, #0\n"          
                "ADD     R12, R11, #0xC\n"  
                "ADD     R1, R11, #8\n"     
                "STR     LR, [R1,R3]\n"     
                "STR     R0, [R12,R3]\n"    
                "STR     R2, [R4,R3]\n"     
                "LDR     R0, [SP]\n"        
                "STR     R0, [R5,R3]\n"     

"loc_FFD53A5C:\n"                            
                                        
                "LDR     R2, =0x71900\n"    
                "LDR     R3, =0x719B4\n"    
                "LDR     R1, [R2]\n"        
                "LDR     R0, [R3]\n"        
                "ADD     R3, R1, #9\n"      
                "CMP     R3, R0\n"          
                "BLS     loc_FFD53A98\n"    
                "LDR     R2, =0x719B0\n"    
                "LDR     R3, [R2]\n"        
                "ADD     R3, R3, R1\n"      
                "RSB     R3, R0, R3\n"      
                "LDR     R0, [SP,#0x10]\n"  
                "ADD     R3, R3, #8\n"      
                "STR     R3, [R0]\n"        
                "B       loc_FFD53AA4\n"    


"loc_FFD53A98:\n"                            
                "ADD     R3, R1, #8\n"      
                "LDR     R1, [SP,#0x10]\n"  
                "STR     R3, [R1]\n"        

"loc_FFD53AA4:\n"                            
                "LDR     R2, [SP,#0x10]\n"  
                "LDR     R1, =0x7195C\n"    
                "LDR     R3, =0x719B4\n"    
                "LDR     R12, [R2]\n"       
                "LDR     R2, [R1]\n"        
                "LDR     R0, [R3]\n"        
                "ADD     R3, R12, R2\n"     
                "CMP     R3, R0\n"          
                "BLS     loc_FFD53AF8\n"    
                "LDR     R2, [SP,#0xC]\n"   
                "RSB     R0, R12, R0\n"     
                "STR     R0, [R2]\n"        
                "LDR     R2, =0x719B0\n"    
                "LDR     R3, [R1]\n"        
                "LDR     R1, [R2]\n"        
                "RSB     R3, R0, R3\n"      
                "LDR     R0, [SP,#8]\n"     
                "STR     R1, [R0]\n"        
                "LDR     R1, [SP,#4]\n"     
                "STR     R3, [R1]\n"        
                "B       loc_FFD53B14\n"    


"loc_FFD53AF8:\n"                            
                "LDR     R0, [SP,#0xC]\n"   
                "STR     R2, [R0]\n"        
                "LDR     R1, [SP,#4]\n"     
                "MOV     R3, #0\n"          
                "STR     R3, [R1]\n"        
                "LDR     R2, [SP,#8]\n"     
                "STR     R3, [R2]\n"        

"loc_FFD53B14:\n"                            
                "LDR     R0, =0x71900\n"    
                "LDR     R1, =0x718FC\n"    
                "LDR     R3, [R0]\n"        
                "LDR     R2, [R1]\n"        
                "CMP     R3, R2\n"          
                "BHI     loc_FFD53B40\n"    
                "LDR     R0, [SP,#0xC]\n"   
                "LDR     R3, [R0]\n"        
                "ADD     R3, R12, R3\n"     
                "CMP     R2, R3\n"          
                "BCC     loc_FFD53904\n"    

"loc_FFD53B40:\n"                            
                "LDR     R1, [SP,#8]\n"     
                "LDR     R2, [R1]\n"        
                "CMP     R2, #0\n"          
                "BEQ     loc_FFD53B74\n"    
                "LDR     R3, =0x718FC\n"    
                "LDR     R1, [R3]\n"        
                "CMP     R2, R1\n"          
                "BHI     loc_FFD53B74\n"    
                "LDR     R0, [SP,#4]\n"     
                "LDR     R3, [R0]\n"        
                "ADD     R3, R2, R3\n"      
                "CMP     R1, R3\n"          
                "BCC     loc_FFD53904\n"    

"loc_FFD53B74:\n"                            
                                        
                "LDR     R3, =0x7195C\n"    
                "LDR     R0, =0x71960\n"    
                "LDR     R2, [R3]\n"        
                "LDR     R3, [R0,#4]\n"     
                "ADD     R2, R2, #0x18\n"   
                "MOV     R1, R2\n"          
                "MOV     R2, #0\n"          
                "CMP     R2, R3\n"          
                "BHI     loc_FFD53BA8\n"    
                "BNE     loc_FFD53BB0\n"    
                "LDR     R3, [R0]\n"        
                "CMP     R1, R3\n"          
                "BLS     loc_FFD53BB0\n"    

"loc_FFD53BA8:\n"                            
                                        
                "MOV     R0, #0x80000005\n" 
                "B       loc_FFD53D24\n"    


"loc_FFD53BB0:\n"                            
                                        
                "LDR     R1, =0x71944\n"    
                "LDR     R0, =0x71990\n"    
                "LDR     R3, [R1]\n"        
                "LDR     R2, [R0]\n"        
                "ADD     R3, R3, R2,LSL#4\n" 
                "ADD     R3, R3, R3,LSL#2\n" 
                "LDR     R12, =0x71960\n"   
                "MOV     R3, R3,LSL#1\n"    
                "ADD     R3, R3, #0xA0\n"   
                "LDR     R2, [R12,#4]\n"    
                "MOV     R0, R3\n"          
                "MOV     R1, #0\n"          
                "CMP     R1, R2\n"          
                "BHI     loc_FFD53BF8\n"    
                "BNE     loc_FFD53C1C\n"    
                "LDR     R3, [R12]\n"       
                "CMP     R0, R3\n"          
                "BLS     loc_FFD53C1C\n"    

"loc_FFD53BF8:\n"                            
                "LDR     R4, =0x71978\n"    
                "LDR     R1, [R4]\n"        
                "CMP     R1, #0\n"          
                "BNE     loc_FFD53C1C\n"    
                "MOV     R0, #0x3140\n"     
                "ADD     R0, R0, #8\n"      
                "BL      sub_FFD6CD44\n"    
                "MOV     R3, #1\n"          
                "STR     R3, [R4]\n"        

"loc_FFD53C1C:\n"                            
                                        
                "LDR     R1, =0x71944\n"    
                "LDR     R0, =0x71990\n"    
                "LDR     R2, [R1]\n"        
                "LDR     R3, [R0]\n"        
                "LDR     R0, =0x71968\n"    
                "ADD     R2, R2, R3,LSL#4\n" 
                "MVN     R3, #0x9F\n"       
                "ADD     R2, R2, R2,LSL#2\n" 
                "ADD     R3, R3, #0x40000000\n" 
                "SUB     R3, R3, R2,LSL#1\n" 
                "LDR     R1, [R0,#4]\n"     
                "MOV     R4, R3\n"          
                "MOV     R5, #0\n"          
                "CMP     R1, R5\n"          
                "BHI     loc_FFD53C68\n"    
                "BNE     loc_FFD53C8C\n"    
                "LDR     R3, [R0]\n"        
                "CMP     R3, R4\n"          
                "BLS     loc_FFD53C8C\n"    

"loc_FFD53C68:\n"                            
                "LDR     R4, =0x71978\n"    
                "LDR     R1, [R4]\n"        
                "CMP     R1, #0\n"          
                "BNE     loc_FFD53C8C\n"    
                "MOV     R0, #0x3140\n"     
                "ADD     R0, R0, #8\n"      
                "BL      sub_FFD6CD44\n"    
                "MOV     R3, #1\n"          
                "STR     R3, [R4]\n"        

"loc_FFD53C8C:\n"                            
                                        
                "LDR     R3, =0x71990\n"    
                "LDR     R0, =0x7192C\n"    
                "LDR     R2, [R3]\n"        
                "LDR     R12, =0x71914\n"   
                "LDR     R1, [R0]\n"        
                "ADD     R3, R2, R2,LSL#2\n" 
                "ADD     R2, R2, R3,LSL#1\n" 
                "LDR     R0, [R12]\n"       
                "RSB     R1, R2, R1\n"      
                "CMP     R0, R1\n"          
                "BLS     loc_FFD53CDC\n"    
                "LDR     R4, =0x71978\n"    
                "LDR     R1, [R4]\n"        
                "CMP     R1, #0\n"          
                "BNE     loc_FFD53CDC\n"    
                "MOV     R0, #0x3140\n"     
                "ADD     R0, R0, #8\n"      
                "BL      sub_FFD6CD44\n"    
                "MOV     R3, #1\n"          
                "STR     R3, [R4]\n"        

"loc_FFD53CDC:\n"                            
                                        
                "LDR     R3, =0x71968\n"    
                "LDR     R12, =0x7195C\n"   
                "LDMIA   R3, {R1,R2}\n"     
                "LDR     R0, [R12]\n"       
                "MOV     R4, #0\n"          
                "MOV     R3, #0x18\n"       
                "ADDS    R1, R1, R0\n"      
                "ADC     R2, R2, #0\n"      
                "ADDS    R1, R1, R3\n"      
                "ADC     R2, R2, R4\n"      
                "CMP     R2, #0\n"          
                "BHI     loc_FFD53D18\n"    
                "BNE     loc_FFD53D20\n"    
                "CMP     R1, #0x40000000\n" 
//                "BLS     loc_FFD53D20\n"    
                 "B       loc_FFD53D20\n"    

"loc_FFD53D18:\n"                            
                "MOV     R0, #0x80000007\n" 
                "B       loc_FFD53D24\n"    


"loc_FFD53D20:\n"                            
                                        
                "MOV     R0, #0\n"          

"loc_FFD53D24:\n"                            
                                        
                "ADD     SP, SP, #0x14\n"   
                "LDMFD   SP!, {R4-R11,PC}\n" 
 );
}



void __attribute__((naked,noinline)) sub_FFD52168_my(){
 asm volatile(
                "STMFD   SP!, {R4-R11,LR}\n" 
                "LDR     R5, =0x715BC\n"    
                "SUB     SP, SP, #0x34\n"   
                "LDR     R3, [R5]\n"        
                "CMP     R3, #3\n"          
                "MOV     R4, R0\n"          
                "MOVEQ   R3, #4\n"          
                "STREQ   R3, [R5]\n"        
                "LDR     R3, =0x7166C\n"    
                "MOV     LR, PC\n"          
                "LDR     PC, [R3]\n"        
                "LDR     R2, [R5]\n"        
                "CMP     R2, #4\n"          
                "BNE     loc_FFD5232C\n"    
                "ADD     R0, SP, #0x30\n"   
                "ADD     R1, SP, #0x2C\n"   
                "ADD     R2, SP, #0x28\n"   
                "ADD     R3, SP, #0x24\n"   
                "BL      sub_FFD5383C_my\n"   //----------------> 
                "CMP     R0, #0\n"          
                "BNE     loc_FFD521E4\n"    
                "LDR     R3, =0x715A8\n"    
                "LDR     R2, [R3]\n"        
                "CMP     R2, #1\n"          
                "BNE     loc_FFD521F8\n"    
                "LDR     R2, =0x71600\n"    
                "LDR     R1, =0x715D4\n"    
                "LDR     R12, [R2]\n"       
                "LDR     R3, [R1]\n"        
                "CMP     R12, R3\n"         
                "BCC     loc_FFD521F8\n"    

"loc_FFD521E4:\n"                           
                "BL      sub_FFD52378\n"    
                "BL      sub_FFD52578\n"    
                "MOV     R3, #5\n"          
                "STR     R3, [R5]\n"        
                "B       loc_FFD5232C\n"    

"loc_FFD521F8:\n"                           
                                        
                "LDR     R12, =0x71608\n"   
                "LDR     R11, =0x71614\n"   
                "LDMIB   R4, {R0-R2}\n"     
                "LDR     R10, [R12]\n"      
                "LDR     R7, [R11]\n"       
                "LDR     R4, [SP,#0x2C]\n"  
                "LDR     R5, [SP,#0x28]\n"  
                "LDR     R6, [SP,#0x24]\n"  
                "LDR     R8, =0x715AC\n"    
                "LDR     R3, [SP,#0x30]\n"  
                "ADD     R12, SP, #0x20\n"  
                "ADD     LR, SP, #0x1C\n"   
                "MOV     R9, #1\n"          
                "STMEA   SP, {R4-R6,R12}\n" 
                "STR     R10, [SP,#0x10]\n" 
                "STR     R7, [SP,#0x14]\n"  
                "STR     LR, [SP,#0x18]\n"  
                "STR     R9, [R8]\n"        
                "BL      sub_FFC87D50\n"    
                "LDR     R3, =0x714C4\n"    
                "MOV     R1, #0x3E8\n"      
                "LDR     R0, [R3]\n"        
                "BL      sub_FFC114CC\n"   
                "CMP     R0, #9\n"          
                "BNE     loc_FFD5226C\n"    
                "BL      sub_FFD5404C\n"    
                "LDR     R3, =0x715BC\n"    
                "LDR     R0, =0xFFD52150\n" 
                "B       loc_FFD52284\n"    

"loc_FFD5226C:\n"                           
                "LDR     R5, [SP,#0x1C]\n"  
                "CMP     R5, #0\n"          
                "BEQ     loc_FFD52290\n"    
                "BL      sub_FFD5404C\n"    
                "LDR     R3, =0x715BC\n"    
                "LDR     R0, =0xFFD5215C\n" 

"loc_FFD52284:\n"                           
                "STR     R9, [R3]\n"        
                "BL      sub_FFD684C4\n"    
                "B       loc_FFD5232C\n"    

"loc_FFD52290:\n"                           
                "BL      sub_FFC87EBC\n"    
                "LDR     R0, [SP,#0x30]\n"  
                "LDR     R1, [SP,#0x20]\n"  
                "BL      sub_FFD53D70\n"    
                "LDR     R4, =0x71600\n"    
                "LDR     R3, [R4]\n"        
                "ADD     R3, R3, #1\n"      
                "LDR     R0, [SP,#0x20]\n"  
                "MOV     R1, R11\n"         
                "STR     R3, [R4]\n"        
                "MOV     R2, R5\n"          
                "BL      sub_FFD52C2C_my\n"    //--------------->
                "LDR     R3, =0x71620\n"    
                "LDR     R1, [R4]\n"        
                "LDR     R2, [R3]\n"        
                "LDR     R12, =0x7161C\n"   
                "MUL     R0, R2, R1\n"      
                "LDR     R1, [R12]\n"       
                "BL      sub_FFEF46F4\n"       
                "LDR     R7, =0x71618\n"    
                "LDR     R3, [R7]\n"        
                "MOV     R4, R0\n"          
                "CMP     R3, R4\n"          
                "BNE     loc_FFD52304\n"    
                "LDR     R6, =0x715B0\n"    
                "LDR     R3, [R6]\n"        
                "CMP     R3, #1\n"          
                "BNE     loc_FFD52320\n"    
                "B       loc_FFD52308\n"    

"loc_FFD52304:\n"                           
                "LDR     R6, =0x715B0\n"    

"loc_FFD52308:\n"                           
                "LDR     R3, =0x71650\n"    
                "MOV     R0, R4\n"          
                "MOV     LR, PC\n"          
                "LDR     PC, [R3]\n"        
                "STR     R5, [R6]\n"        
                "STR     R4, [R7]\n"        

"loc_FFD52320:\n"                           
                "LDR     R2, =0x715AC\n"    
                "MOV     R3, #0\n"          
                "STR     R3, [R2]\n"        

"loc_FFD5232C:\n"                           
                                        
                "ADD     SP, SP, #0x34\n"   
                "LDMFD   SP!, {R4-R11,PC}\n" 

                "MOV     PC, LR\n"          
 );
}


void __attribute__((naked,noinline)) movie_record_task(){

 asm volatile(
                "STMFD   SP!, {R4,LR}\n"    
                "SUB     SP, SP, #4\n"      
                "MOV     R4, SP\n"          
                "B       loc_FFD51A90\n"    

"loc_FFD519EC:\n"                           
                "LDR     R3, =0x715A0\n"    
                "LDR     R2, [R3]\n"        
                "CMP     R2, #0\n"          
                "BNE     loc_FFD51A7C\n"    
                "SUB     R3, R12, #2\n"     
                "CMP     R3, #9\n"          
                "LDRLS   PC, [PC,R3,LSL#2]\n" 
                "B       loc_FFD51A7C\n"    

                ".long loc_FFD51A3C\n"
                ".long loc_FFD51A54\n"
                ".long loc_FFD51A5C\n"
                ".long loc_FFD51A64\n"
                ".long loc_FFD51A44\n"
                ".long loc_FFD51A6C\n"
                ".long loc_FFD51A4C\n"
                ".long loc_FFD51A7C\n"
                ".long loc_FFD51A74\n"
                ".long loc_FFD51A34\n"

"loc_FFD51A34:\n"                           
                                        
                "BL      sub_FFD51B28\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A3C:\n"                           

                "BL      unlock_optical_zoom\n"                        
                "BL      sub_FFD51CDC\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A44:\n"                           
                                        
                "BL      sub_FFD52168_my\n"   //----------------> 
                "B       loc_FFD51A78\n"    

"loc_FFD51A4C:\n"                           
                                        
                "BL      sub_FFD5259C\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A54:\n"                           
                                        
                "BL      sub_FFD52400\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A5C:\n"                           
                                        
                "BL      sub_FFD5270C\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A64:\n"                           
                                        
                "BL      sub_FFD528D0\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A6C:\n"                           
                                        
                "BL      sub_FFD52624\n"    
                "B       loc_FFD51A78\n"    

"loc_FFD51A74:\n"                           
                                        
                "BL      sub_FFD52450\n"    

"loc_FFD51A78:\n"                           
                                        
                "LDR     R1, [SP]\n"        

"loc_FFD51A7C:\n"                           
                                        
                "LDR     R3, =0x714D4\n"    
                "MOV     R2, #0\n"          
                "STR     R2, [R1]\n"        
                "LDR     R0, [R3]\n"        
                "BL      sub_FFC10D38\n" 

"loc_FFD51A90:\n"                           
                "LDR     R3, =0x714D0\n"    
                "MOV     R1, R4\n"          
                "LDR     R0, [R3]\n"        
                "MOV     R2, #0\n"          
                "BL      sub_FFC10920\n" 
                "LDR     R0, [SP]\n"        
                "LDR     R12, [R0]\n"       
                "CMP     R12, #0xC\n"       
                "MOV     R1, R0\n"          
                "BNE     loc_FFD519EC\n"    
                "LDR     R3, =0x714CC\n"    
                "LDR     R0, [R3]\n"        
                "BL      sub_FFC116B4\n"   
                "BL      sub_FFC11E7C\n"        
                "ADD     SP, SP, #4\n"      
                "LDMFD   SP!, {R4,PC}\n"    

 );
}

