#include "stubs_asm.h"

//NHSTUB(VbattGet, 0xFFC1C12C)
//NHSTUB(GetZoomLensCurrentPosition, 0xFFE8F684)
//NHSTUB(GetZoomLensCurrentPoint, 0xFFE8F670)
//NHSTUB(GetFocusLensSubjectDistance, 0xFFEA2F3C)

//NHSTUB(GetSystemTime, 0xFFC04D38)
//NHSTUB(GetPropertyCase, 0xFFC14DEC)
//NHSTUB(SetPropertyCase, 0xFFC14C9C)

//NHSTUB(malloc, 0xFFF00AC0)
//NHSTUB(free, 0xFFF00ACC)

//NHSTUB(AllocateMemory, 0xFFC01AB0)
//NHSTUB(FreeMemory, 0xFFC01ABC)
//NHSTUB(CreatePhysicalVram, 0xFFD37D50)
//NHSTUB(DisplayImagePhysicalScreen, 0xFFD36FE0)
//NHSTUB(PhySw_testgpio, 0xFFC1889C)
//NHSTUB(RefreshPhysicalScreen, 0xFFD8752C)
//NHSTUB(isalpha, 0xFFEF4E7C)
//NHSTUB(isdigit, 0xFFEF4EAC)
//NHSTUB(islower, 0xFFEF4EDC)
//NHSTUB(isspace, 0xFFEF4F24)
//NHSTUB(isupper, 0xFFEF4F3C)
//NHSTUB(rand, 0xFFEF8360)
//NHSTUB(srand, 0xFFEF8384)

//NHSTUB(IsStrobeChargeCompleted, 0xFFD11B24)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFFE97EB0)  //null stub
NHSTUB(WriteSDCard, 0xFFC702A4)
NHSTUB(GetDrive_ClusterSize, 0xffc607b0)
NHSTUB(GetDrive_TotalClusters, 0xffc607ec)
NHSTUB(GetDrive_FreeClusters, 0xffc60828)
NHSTUB(PostLEDMessage, 0xFFC1D7C4)
NHSTUB(TurnOffMic,  0xFFC1E944) 
NHSTUB(TurnOnMic,   0xFFC1E908) 
NHSTUB(ExpCtrlTool_StopContiAE,  0xFFD0018C) 
NHSTUB(ExpCtrlTool_StartContiAE, 0xFFD0015C) 
NHSTUB(MakeAFScan,  0xFFD5D538) 
NHSTUB(GetBatteryTemperature, 0xFFC1D200)
NHSTUB(GetCCDTemperature, 0xFFC1D1EC)
NHSTUB(GetOpticalTemperature, 0xFFC1D1D8)
NHSTUB(PT_PlaySound, 0xFFD67DB8)

NHSTUB(EnterToCompensationEVF, 0xffd58f08) 
NHSTUB(ExitFromCompensationEVF, 0xffd5c524) 
NHSTUB(SetAE_ShutterSpeed, 0xFFEB9144)
