#include "stubs_asm.h"

//NHSTUB(VbattGet, 0xFFC1B4CC)
//NHSTUB(GetZoomLensCurrentPosition, 0xFFE533F8)
//NHSTUB(GetZoomLensCurrentPoint, 0xFFE533E4)
//NHSTUB(GetFocusLensSubjectDistance, 0xFFE66B78)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFFD5B3B0)  //null stub
NHSTUB(GetDrive_ClusterSize, 0xffc5c270)
NHSTUB(GetDrive_TotalClusters, 0xffc5c2ac)
NHSTUB(GetDrive_FreeClusters, 0xffc5c2e8)
NHSTUB(TurnOffMic, 0xffc1ec78)
NHSTUB(TurnOnMic, 0xffc1ec30)

NHSTUB(ExpCtrlTool_StopContiAE,  0xFFCE0940) 
NHSTUB(ExpCtrlTool_StartContiAE, 0xFFCE0928) 
NHSTUB(MakeAFScan,  0xFFD37B38) 
