#include "stubs_asm.h"

//NHSTUB(VbattGet, 0xFFC1B4AC)
//NHSTUB(GetZoomLensCurrentPosition, 0xFFE59D2C)
//NHSTUB(GetZoomLensCurrentPoint, 0xFFE59D18)
//NHSTUB(GetFocusLensSubjectDistance, 0xFFE6D4AC)

NHSTUB(malloc, 0xFFEC5BC0)
NHSTUB(free, 0xFFEC5BCC)

//NHSTUB(isalpha, 0xFFEB8A94)
//NHSTUB(isdigit, 0xFFEB8AC4)
//NHSTUB(islower, 0xFFEB8AF4)
//NHSTUB(isspace, 0xFFEB8B3C)
//NHSTUB(isupper, 0xFFEB8B54)
//NHSTUB(rand, 0xFFEBBF78)
//NHSTUB(srand, 0xFFEBBF9C)

NHSTUB(SetZoomActuatorSpeedPercent, 0xFFC19688)  //null stub
